### ISSUE TITLE
HERE Geocoder

### ISSUE THREAD

**Issue by jwmail** [stefanocudini/leaflet-search#102]
Hi, 

Just found your leaflet search plugin. I was wondering if adding another geocoder was possible: HERE Maps. (https://developer.here.com/rest-apis/documentation/geocoder)

Thanks,
JW

**Comment by sackh** [comment]
@stefanocudini - is this supported already? I would also like this feature in `leaflet-search`. Let me know I will give it a try if not implemented already. Let me know if this is feasible.

**Comment by stefanocudini** [comment]
> Just found your leaflet search plugin. I was wondering if adding another geocoder was possible: HERE Maps.

The plugin search support any geocoder! look at te code here:
https://github.com/stefanocudini/leaflet-search/blob/master/examples/custom-source-data.html

integrated support of 3rd party services is work in progrsss:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search-geocoder.js

I'm accept PR
many tnks

**Comment by stefanocudini** [comment]
> @stefanocudini - is this supported already? I would also like to have this feature in `leaflet-search`. Let me know I will give it a try if not implemented already. Let me know if this is feasible.

this would be a great welcome contribution ..

I had started to create the structure for an integration of the most famous online geocoders, this is the starting point

a mapping of the services (url, return parameters) and then simply a callback for each datasource:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search-geocoder.js

**Comment by stefanocudini** [comment]
> @stefanocudini - is this supported already? I would also like to have this feature in `leaflet-search`. Let me know I will give it a try if not implemented already. Let me know if this is feasible.

this would be a great welcome contribution ..

I had started to create the structure for an integration of the most famous online geocoders, this is the starting point

a mapping of the services (url, return parameters) and then simply a callback for each datasource:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search-geocoder.js

among the new input options for this features there should only be:
- service name
- api username
- api key

**Comment by stefanocudini** [comment]
@sackh I was looking at the documentation and integration examples and wanted to ask you what technology here uses for the engine of api. Did you rely on any open source search engine such as Pelias?

**Comment by sackh** [comment]
@stefanocudini - I am not aware of internal implementation.
