### ISSUE TITLE
Search control events

### ISSUE THREAD

**Issue by wenszxc** [stefanocudini/leaflet-search#105]
How can I catch the "search_expanded" event from the search control?

I have already done the following approaches but still didn't work

`$scope.$on("search_expanded", function(e){ console.log("search expanded") });`

`$(document).on("search_expanded", function(e){ console.log("search expanded") });)`

    leafletData.getMap().then(function(map) {
                       map.on('search_expanded', function(e){
                            alert("search control expanded");
                       });
                   });

**Comment by elosoman** [comment]
I've been able to trap this event ...

```
var searchControl = new L.Control.Search({});
map.addControl( searchControl );
searchControl.on('search_collapsed', function(e) {
    console.log('search_collapsed', e);
})
```
