### ISSUE TITLE
Geojson search text with %..%

### ISSUE THREAD

**Issue by SilentT-FR** [stefanocudini/leaflet-search#108]
http://labs.easyblog.it/maps/leaflet-search/examples/geojson-layer.html
If you write "ama" for alabama any result

**Comment by reyemtm** [comment]
This is part of the options, it is true by default.
```
initial: true,				//search elements only by initial text
```
It is set to false in the [simple](http://labs.easyblog.it/maps/leaflet-search/examples/simple.html) search example - try searching 'yan' for cyan. There may be a performance reason why it is initially set to true, not sure. There a lots of other options that can be seen [here](https://github.com/stefanocudini/leaflet-search/blob/master/dist/leaflet-search.src.js).

**Comment by SilentT-FR** [comment]
Thanks.

**Comment by SilentT-FR** [comment]
and sorry for the noise
