### ISSUE TITLE
Setup with geoJSON data

### ISSUE THREAD

**Issue by elosoman** [stefanocudini/leaflet-search#109]
Great plugin ... although I've had some issues getting my geoJSON layers to be searched. I have used the geoJSON example as the basis for this code.

So i've loaded 4 geoJSON layers into the map which all display fine and i'm initializing the search control as

```
var searchLayer = L.geoJson(geojsonData, geojsonOpts);
var searchControl = new L.Control.Search({
    layer: searchLayer,
    propertyName: 'name', 
});
map.addControl( searchControl );
```

When a search is performed i get the following error from the plugin ...

```
Uncaught TypeError: Cannot read property 'lat' of undefined
```

If I follow the example for multiple layers and pass a layergroup to the search control

```
var searchLayer = L.layerGroup([L.geoJson(geojsonData, geojsonOpts)]);
var searchControl = new L.control.search({
    layer: searchLayers,
    propertyName: 'name', 
});
```

 ... this is the error returned.

```
Uncaught TypeError: m.getLatLng is not a function
```

Suggestions on why it would be failing with both of these approaches?

**Comment by reyemtm** [comment]
How are you loading your geojson? If the search is called before the geojson is fully loaded it will fail. For most of the search examples the geojson files are extremely small, so there is no need, but if you are loading a several mb file, then you might have issues. For example, if you are using omnivore, you should call the search after the 'ready' event, or 'loaded' if using the ajax plugin.

The second issue could be related to whether the search plugin is looking for a point, line or polygon. If it is searching either a line or polygon, and tries to get the latlng it will fail. That one might be a little harder to track down. Live example would be helpful.

**Comment by elosoman** [comment]
So this layers to the map are being loaded after the dom is rendered. I'm call $.getJSON() and the init comes after the geojson file is loaded.

The geojson file is 1000k line and about 33k so i don't think its a space issue. All of my features are type='Polygon' as in ...

`
        {
            "type": "Feature",
            "id": "relation/-24972",
            "properties": {
                "type": "relation",
                "id": -24972,
                "tags": {
                    "catalog_id": "405",
                    "name": "S.E. Lobby C Level 0",
                    "type": "multipolygon"
                },
                "relations": [],
                "meta": {}
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [
                            -71.04621081761,
                            42.34426720384
                        ],
                        [
                            -71.04615081969,
                            42.34422752727
                        ],
                        [
                            -71.04608199538,
                            42.34428809437
                        ],
                        [
                            -71.04610436902,
                            42.34430176224
                        ],
                        [
                            -71.04607101547,
                            42.34433010823
                        ],
                        [
                            -71.04633806981,
                            42.3445023566
                        ],
                        [
                            -71.04637389108,
                            42.34447187429
                        ],
                        [
                            -71.04643786434,
                            42.34451417959
                        ],
                        [
                            -71.0465029658,
                            42.34446040086
                        ],
                        [
                            -71.04621081761,
                            42.34426720384
                        ]
                    ]
                ]
            }
        },
`

Should there be any difference in how its being constructed (i.e., new L.Control.Search or new L.control.search)?

I'll try for a live example as this is linked to some internal resources which are not available on the general internet.

**Comment by elosoman** [comment]
So just another update ... it appears that if I follow your examples for geoJson ... I'm getting a combination of the map layer control and a display of all the layers when they are added to the search control and then the search control to the map. Should there be any consideration for using the search plugin with the layer control?

**Comment by stefanocudini** [comment]
see the update here: #171
