### ISSUE TITLE
Leaflet V1.0.0-beta.2 compatibillity...

### ISSUE THREAD

**Issue by dwickins** [stefanocudini/leaflet-search#110]
Hi,
I'm using the leaflet-search plugin in conjunction with the Bing maps layer plugin. The Bing maps layer plugin requires V1.0.0 of leaflet in order to work. The leaflet-search plugin appears to work fine with the newer version of leaflet except one small detail. When performing a search it's not possible to use the enter key to complete the search, it's only possible to click on the search button. Looking at the JS in leaflet 0.7.2 I'm guessing it's related to this piece of code which is different/missing in 1.0.0:

	_onKeyPress: function (e) {
		if (e.keyCode === 13) {
			this.fire('click', {
				originalEvent: e,
				latlng: this._latlng
			});
		}
	}

Has anyone else come across same problem or know of a solution...

**Comment by stefanocudini** [comment]
@dwickins I understood the problem, but I can't find a solution... 
Do you have any updates?

**Comment by stefanocudini** [comment]
solved from version 2.2.0
