### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by MuellerMatthew** [stefanocudini/leaflet-search#115]
There is a bug with the case sensitivity regex(line 373) where it is generating an error if the original text contains '(' or ')' or '\'. It appears that the regex on line 366 isn't fully sanitizing the text before it gets to the RegExp on line 373.

Example:
http://labs.easyblog.it/maps/leaflet-search/examples/google-geocoding.html
-type in anything with the above mentioned special characters and you will get a console error.

**Comment by stefanocudini** [comment]
solved from version 1.9.2
