### ISSUE TITLE
What happened to zoom option?

### ISSUE THREAD

**Issue by reyemtm** [stefanocudini/leaflet-search#118]
Why not just leave this in for backwards compatibility in the showLocation on line 823? Really don't feel like change all my map code.

    if(this.options.zoom)
      this._map.setView(latlng, this.options.zoom);
    else
      this._moveToLocation(latlng, title, this._map);

**Comment by stefanocudini** [comment]
Removed! From version 1.9.1 
https://github.com/stefanocudini/leaflet-search/releases/tag/v1.9.1

in place is added a new option *moveToLocation: function()* that offers more possibilities in additionof zoom level

**Comment by reyemtm** [comment]
Ok, thanks.
