### ISSUE TITLE
Zoom removed?

### ISSUE THREAD

**Issue by caycek** [stefanocudini/leaflet-search#119]
In what I'm pretty sure is the previous version of the current there was a zoom option. For some reason this has been removed?? 

I'm not going to be able to upgrade without it in the future.

**Comment by reyemtm** [comment]
Just add the code I show in the closed issue,  it adds the zoom option back. 

https://github.com/stefanocudini/leaflet-search/issues/118

**Comment by stefanocudini** [comment]
I will leave this issue opened for any times to see if there are other users need this option

**Comment by adegreiff** [comment]
also missing the zoom function.

**Comment by stefanocudini** [comment]
It's re-enabled zoom option from version **1.9.9**
