### ISSUE TITLE
Controls disappear sometimes

### ISSUE THREAD

**Issue by NeilSelkirk** [stefanocudini/leaflet-search#121]
Hi,

I was testing the leaflet-search and noticed that the controls disappear sometimes.

Try this:
1) Go to (http://labs.easyblog.it/maps/leaflet-search/examples/nominatim.html) [http://labs.easyblog.it/maps/leaflet-search/examples/nominatim.html]
2) In the search field, enter southwark
3) Select first option
Result: Map moves & controls disappear
User is then unable to continue the test...

4) In the search field, enter waterloo east
5) Select first option

Here's a video of the controls disappearing when southwark is entered: http://screencast.com/t/CGXGfD8WuoGS

Chrome version: Version 50.0.2661.102 m

Please note: I was unable to consistently demonstrate this error, so it may be a timing related bug due to Internet response times.

The only error thrown on the Chrome Developer Tools console is a not found for http://labs.easyblog.it/favicon.ico (which is unrelated).

Neil

**Comment by stefanocudini** [comment]
uoh!! strange! Idon't know!  may be it happen when the string in tooltips items is too long!

**Comment by NeilSelkirk** [comment]
Hi Stefano,
Here's another example that seems to fail.  Just paste the following into the search field and then choose the only result.

Katoope street, Wanguri

**Comment by stefanocudini** [comment]
mmmhh then is not a problem of length of string

**Comment by yporret** [comment]
same problem here.

look like the controler is move outside the view (to the left if we have the default setting "position: topleft"). And you can eventually get it back if you play with the zoom for a few minutes.

I can't reproduce the problem with "position: topright" (but the options display is broken).
