### ISSUE TITLE
moveToLocation not Refreshing Labels

### ISSUE THREAD

**Issue by TranquilAbyss** [stefanocudini/leaflet-search#127]
I have found an issue with the `moveToLocation` where the Leaflet Labels layers will not redraw, instead they stay in the same place on the screen from before the move. 

Here is the code.
```
searchControl = L.control.search({
	layer: poiLayers,
	propertyName: 'name',
	moveToLocation: function(latlng, title, map) {
		var zoom = 2;
		map.setView(latlng, zoom); // access the zoom				
	}
}).addTo(map);
```

Leaflet Labels are part of the Overlay container. The map is also part of the overlay container and it appear to stay stationary. 

The labels should be under the markers but those markers are from other places on the map.
![](http://image.prntscr.com/image/b0677207fb7a424084b88884f15fa76d.png)

**Comment by TranquilAbyss** [comment]
I should add that I tried using `map._onResize();` but it did not change anything. 

Also the problem only happens when the map is zoomed in and the marker being searched for is off screen.

**Comment by stefanocudini** [comment]
I don't understood the problem... do you have a jsfiddle code or a demo online?

**Comment by TranquilAbyss** [comment]
This maybe a Leaflet Label problem or just a general Leaflet problem of some kind. I found a similar issue over on the Leaflet Label Git. https://github.com/Leaflet/Leaflet.label/issues/142
