### ISSUE TITLE
Add a reference property

### ISSUE THREAD

**Issue by TranquilAbyss** [stefanocudini/leaflet-search#137]
Please add a reference property that can be used with the `propertyName` / key. `propertyName` could be the default value. 

A new option called `propertyRef`would allow for a different key to be used instead or the name. This would allow objects that share the same name to be separated in the result list. `propertyNames` will still be used to display the names in the result list and be the attribute being searched.

An Example of the setup

```
var poiLayers = L.featureGroup([
  defaultLayers,
  cityLayers,
  animalLayers,
  resourceLayers
]);

searchControl = L.control.search({
  layer: poiLayers,
  propertyName: 'name',
  propertyRef: 'id',
  moveToLocation: function(latlng, title, map) {
    var zoom = 2;
    map.setView(latlng, zoom); // access the zoom
  }
}).addTo(map);
```

Let me know if you have any questions.

Thanks.

**Comment by Ju-ens** [comment]
I assume this could be an answer to https://github.com/stefanocudini/leaflet-search/issues/131 and https://github.com/stefanocudini/leaflet-search/issues/147
Ok for the idea to add a new option `propertyRef`, but how modify the plugin code for taking account of it ?

Somwhere in the  `_defaultFormatData`: 
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L417
and/or
the `_recordsFromLayer` functions:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L516

Is there a working example ?

Thanks

**Comment by TranquilAbyss** [comment]
I took some classes in database design so the problem to me looks like a lack of unique identifiers to represent each piece of data. I know this is not a relational database but the rules are still useful and can be found here. [https://en.wikipedia.org/wiki/Codd%27s_12_rules](https://en.wikipedia.org/wiki/Codd%27s_12_rules)

I am no expert with JavaScript nor know coding library too well l but ill take an attempt at a fix.

The easiest solution and cleanest solution I can think of is to replace `propName `or `propertyName ` in your code with pseudo code below in both functions.
`(propertyRef != null) ? propertyRef : propName;`

Basically if a property reference (aka unique ID) is selected then use it instead of the property name. But then return a list of property names.

Some explanation if needed below:

Example line from `_recordsFromLayer` function (there are more than one line to change)
currently: `retRecords[ _getPath(layer.options,propName) ] = loc; `
This line of code is in a foreach loop and if more than one layer has the same name, then the last layer get the position using that name in the array. If the are unique IDs  then it wont over write the item
For example if the follow list of objects is used  `[(name: "apple", id:1), (name: "apple", id:2)] `
Using the name "apple" will only return the object with ID of 2. 
But if `(propertyRef != null) ? propertyRef : propName;` is used inplace of `propName` then the `propertyRef `is checked (if assigned) and you will get both objects named "apple" in the result list.

Example line from `_defaultFormatData` function (there are more than one line to change)
currently: `jsonret[ _getPath(json[i],propName) ]= L.latLng( json[i][ propLoc[0] ], json[i][ propLoc[1] ] );`
Similar thing looks like it is happening here where the prop name is in someway the reference to the object. If two objects have the same name then... I don't know what happens here.... but I think it could be replaced the same way.

This is a untested and incomplete fix but I hope this helps. I have not tried to fix this problem since it has not been a priority for me.
