### ISSUE TITLE
Search multiple values?

### ISSUE THREAD

**Issue by augustobg** [stefanocudini/leaflet-search#138]
It is possible to search multiple comma-separated values at the same time?

**Comment by stefanocudini** [comment]
???

**Comment by augustobg** [comment]
Hmm,

Using your simple example:
You can search for "black", click on the drop down option, and it will take you to that marker.
My question is: can I look out for "black, cyan, blue" at the same time?
Maybe not take me to multiple locations,  but draw the little circles around those markers.

Thanks for the response.




On Wed, Sep 28, 2016 at 6:42 AM -0500, "Stefano Cudini" <notifications@github.com<mailto:notifications@github.com>> wrote:


???

-
