### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by augustobg** [stefanocudini/leaflet-search#144]
Im getting this error on console after using the search option for looking for a polygon.
(using leaflet with some geojson polygons) 

Uncaught TypeError: Cannot set property '_leaflet_pos' of undefined(…)

Any ideas?

**Comment by stefanocudini** [comment]
what version of Leaflet?

**Comment by augustobg** [comment]
1.0

Obtener Outlook para Android<https://aka.ms/ghei36>



On Mon, Nov 21, 2016 at 5:46 AM -0600, "Stefano Cudini" <notifications@github.com<mailto:notifications@github.com>> wrote:


what version of Leaflet?

-
