### ISSUE TITLE
Markers within radius leaflet

### ISSUE THREAD

**Issue by jagb1007** [stefanocudini/leaflet-search#145]
Leaflet markers within a radius:

Good morning can help me with some tutorial, where I can draw a marker anywhere on the map and by a combo box can choose a distance and I can draw a circle by seeing the names of markers that are in that circle, something like that

**Comment by reyemtm** [comment]
this doesnt seem like a search issue - you want to look into turf.js - I think there is even an example for just what you are talking about. Here is one example - http://turfjs.org/examples/turf-within/ - be careful though, different versions of turf have different capabilities.

**Comment by stefanocudini** [comment]
tnk @reyemtm
