### ISSUE TITLE
GeoJSON shows only one result

### ISSUE THREAD

**Issue by antoniosprza** [stefanocudini/leaflet-search#147]
Hi, i have a situation about the leaflet-search, in my js archive with the data for geojson, the search only appears the first result, but in the archive are many result with the same result, i'm from mexico and not found much information about this situation.

I'm searching with a field of the json, how can i solve the problem? I need to show all of the result of the field.

**Comment by iqnaul** [comment]
Hi, I'm also having similar issue. I have more than one exact same villages name in my geojson layer, but leaflet-search only showed the first one. What is the method to solve this?

**Comment by kamilglod** [comment]
@iqnaul it's because `_defaultFilterData ` method removes duplicated records. You can override that method by passing `filterData: (text, records) => records` to the config.

**Comment by Ju-ens** [comment]
@kamilglod coul you be more specific : where do you pass the filterData method, in the plugin code or in the plugin options ?
I try several ways but nothing works.

I had also a look at https://github.com/stefanocudini/leaflet-search/issues/131 which looks like the same and is unsolved,
thanks

**Comment by kamilglod** [comment]
@iqnaul just put it into the configuration object during initialization:
```
map.addControl( new L.Control.Search({
    position: 'topright',
    minLength: 3,
    ...
    filterData: (text, records) => records,
}) );
```
by default this method is used: https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L398
which remove duplicated results by passing them as a key to the object.

**Comment by Ju-ens** [comment]
Thanks @kamilglod you're right about the method wich removes duplicate, but it seems when passing the filterData method you propose, leaflet-search sends back all records as result without searching !

Here's my code:

    var searchControl = new L.Control.Search({
        position : 'topleft',
        layer: myLayer,
        propertyName: 'myLayerPropertiesName',
        initial: false,
        collapsed: false,
        marker: false,
        filterData: (text, records) => records,
    }).addTo(map);

    searchControl.on('search:locationfound', function(e) {   // Higlight the search result
        e.layer.setStyle(highLight);        
        e.layer.bringToFront();
    });

Any clue ?

**Comment by kamilglod** [comment]
@Ju-ens sorry, I made a mistake: I mixed `filterData` with `formatData`. I'll provide an example how to override those methods to render multiple records (if it's possible) today evening. I see that it's more complicated.

**Comment by kamilglod** [comment]
@Ju-ens Ok, I worked it out, however it wasn't easy :) the main problem is that we're working by default with JS object as results data instead of JS array. So we need to force this plugin to accept and use arrays. Here is an example code, notice that you need to extend default plugin class:
```
const MultipleResultsLeafletSearch = LeafletSearch.extend({
  _defaultFilterData: (text, records) => records,
  _defaultFormatData: json => json,
  _createTip: function (i, obj) {
    return new LeafletSearch()._createTip.call(this, obj.title, obj.loc);
  },
})
```
and then use it as normal 
```
this.map.addControl(new MultipleResultsLeafletSearch({
  marker: false,
  minLength: 3,
  position: 'topright',
  ...
})
```
1. you need to pass data from the server through the `_defaultFormatData` and `_defaultFilterData` methods, you can modify them as you need, add some custom filters like filter by keyword - it should be easy - just check original methods. 
2. then  `LeafletSearch` iterate through all the records and pass every result to the `_createTip` method (https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L428)
in original code it was accepting text and a location object, you'll receive what you return from the server + how did you modify that data in `_defaultFormatData` method. We can call orginal `_createTip` method by fetching `title` and `location` object from our object. We need to use `.call` to give `_createTip` proper scope.
Hope this is clear :)

**Comment by Ju-ens** [comment]
Thanks @iqnaul !

I have something wrong or misunderstood your method, sorry, trying what you propose, the search results are always 'undefined'...

I think i am missing something about how you modified the `_createTip` 

Here's my code:
```
const MultipleResultsLeafletSearch = L.Control.Search.extend({
        _defaultFilterData: (text, records) => records,
        _defaultFormatData: json => json,
        _createTip: function (i, obj) {
            return new L.Control.Search()._createTip.call(this, obj.title, obj.loc);
        },
})

var searchControl = new MultipleResultsLeafletSearch({
        position : 'topleft',
        layer: myLayer
        propertyName: 'myLayerPropertiesName',
}).addTo(map);

searchControl.on('search:locationfound', function(e) {	// Higlight the search result
	e.layer.setStyle(highLight);
        e.layer.bringToFront();
});
```
Anyway, you're right about the arrays, it's a TODO thing:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L720
I wonder if the `_recordsFromLayer` has to be overridden as well

**Comment by kamilglod** [comment]
@Ju-ens I'm not @iqnaul but never mind ;)
your `obj` structure is probably differs from mine, add `console.log(obj)` to `_createTip` method.

**Comment by iqnaul** [comment]
Hi @Ju-ens I think you misread, it was @kamilglod who gave a suggestions to you 👍 
Anyway thank you for both of you!

**Comment by Ju-ens** [comment]
@iqnaul @kamilglod sorry for mistaking

@kamilglod, thanks again, my `obj` comes from a geojson with the following structures

```
o.LatLng {lat: 48.8737639820001, lng: 2.32002716900007, alt: -100000, layer: e}
alt : -100000
lat : 48.8737639820001
layer : e
     defaultOptions : Object
     feature : Object
          geometry : Object
          properties : Object
          type : "Feature"
          __proto__ : Object
     options : Object
     __parent : e
     _eventParents : Object
     _events : Object
     _initHooksCalled : true
     _latlng : o.LatLng
     _leaflet_id : 7392
     _map : null
     _mapToAdd : null
     _path : path
     _point : o.Point
     _pxBounds : o.Bounds
     _radius : 4
     _renderer : e
     _zoomAnimated : true
     __proto__ : e
lng : 2.32002716900007
__proto__ : Object
```
I changed `obj `with `obj.layer.feature.properties` and `obj.layer.feature.geometry`

```
_createTip: function (i, obj) {
            console.log(obj);
            return new L.Control.Search()._createTip.call(this, obj.layer.feature.properties.Name, obj.layer.feature.geometry.coordinates);
}
```
The search results are no longer undefined but it still does not work...

**Comment by kamilglod** [comment]
@Ju-ens I created a jsfiddle example http://jsfiddle.net/Lt4y9wkv/1/ but now I see that we need to override `_getLocation` method too. End even with it, we still have a problem: we cannot recognise which button with the same value has been selected. In that fiddle example we're selecting first location with equal `title` but it does work properly only for the first result on the list. So I don't see an elegant way to handle it without rewriting half of this plugin.

How about adding whitespaces to titles to make them unique? http://jsfiddle.net/vvand09c/ dummy but works :)

**Comment by Ju-ens** [comment]
@kamilglod I don't think we really want to rewrite the plugin :-)

So what about using unique ID for each records ?
(see answer of @TranquilAbyss for general idea https://github.com/stefanocudini/leaflet-search/issues/137)

We can create a new field (index) to search, with a function like this (where ID has been added to data source as unique number, geojson in my case, probably better than whitespaces):

```
function onEach(feature, layer) {         
        var p = layer.feature.properties;
        p.index = p.Name + " | "+ p.ID;
    }
```

Then use index as parameter for the plugin:

```
var searchControl = new L.Control.Search({
       layer: myLayer,
       propertyName: 'index',
       ...
}).addTo(map);
```
It works fine without rewriting and allows to add several fields to search if necessary.

The last matter is the result list which shows the ID field... It would be better if we could search on a concatenated field but show only one in the results
I guess we can use formatData for that ?

**Comment by Ju-ens** [comment]
Ok I solved my last point, we can customize the result list by passing a buildTip  function in the plugin options: 

```
var searchControl = new L.Control.Search({
      ...
      buildTip: function(text, val) {
          var p = val.layer.feature.properties;
          var tip = p.Name;
          return '<a href="#" class="">'+tip+'</a>';
}
```
Even if we search on a concatenated field (for example Name + ID), the result will show only the selected value (Name) but will not remove duplicate results because using a unique ID there is no more.

This supposed to have a unique ID field but works without rewriting.
One way could be ti use leaflet id instead of personal one, but I have never been comfortable with that!
