### ISSUE TITLE
Google geocoding doesn't find certain locations

### ISSUE THREAD

**Issue by jekuno** [stefanocudini/leaflet-search#148]
`leaflet-search` doesn't deliver any results for certain locations even though the Google geocode service knows them.

**Example:**
If you search for _Pontinia_ using http://labs.easyblog.it/maps/leaflet-search/examples/google-geocoding.html you don't get any results.

If you search for _Pontinia_ using https://maps.googleapis.com/maps/api/geocode/json?address=Pontinia you get the correct result.

This seems to be a bug. Is there any quick workaround?

**Comment by jekuno** [comment]
Could anybody try the life example (see above) and confirm that it's a bug?

**Comment by jlengrand** [comment]
I experience the same behaviour as you indeed. I suspect this does not come from the library itself, but rather from the geocoding service that is being used in the background.

**Comment by jekuno** [comment]
Doesn't the example above prove that the Google geocode service knows the location but leaflet-search doesn't deliver the result for some reason? Or am I missing something here?

**Comment by jlengrand** [comment]
Yes, that is pretty much what I was saying :).
I would have to look deeper but It seems to me like leaflet-search is just an interface to another geocoding API in the background. 
I would suspect that the results would be the same if leaflet-search was using Google's geocoding API. 
Apparently it doesn't, and I would expect the service that is being used is less complete than the Google one. 

Sorry if it is a bit fuzzy, I discovered about this library this morning and I don't know the inner workings yet.

**Comment by dramaking** [comment]
@jekuno I had the same issue. Then I checked the "filterData" option and found out that if you don't set it up, a default filter will be applied which search for the text input in the address returned from google.

Just write a customised filter function and return the same records:
```
filterData(text, records) {
  return records
},
```

**Comment by stefanocudini** [comment]
exactly @dramaking
