### ISSUE TITLE
add setTimeout to marker

### ISSUE THREAD

**Issue by kaio328** [stefanocudini/leaflet-search#149]
Where to add a setTimeout function?

i tried:
`	showLocation: function(latlng, title) {	
			
		if(this.options.zoom)
			this._map.setView(latlng, this.options.zoom);
		
			this._map.panTo(latlng);                                                    

		if(this._markerLoc)
		{
			this._markerLoc.setLatLng(latlng);  
			this._markerLoc.setTitle(title);
			this._markerLoc.show();
			this._markerLoc.bindPopup(title);
			this._markerLoc = setTimeout(function() {
			this._markerLoc.hide()
			},1000);
			if(this.options.animateLocation)
				this._markerLoc.animate();
	
		}
		
		if(this.options.autoCollapse)
			this.collapse();
		return this;
	}
});`

not working...

**Comment by stefanocudini** [comment]
*this* inside setTimeout() is not the same of this outside

**Comment by kaio328** [comment]
Thanks for your adivce! Could figure it out 👍
