### ISSUE TITLE
Remove this._markerLoc() in index.html

### ISSUE THREAD

**Issue by kaio328** [stefanocudini/leaflet-search#151]
Hey,

i really cant figute out how to remove or hide `this._markerLoc()` via code in the index.html.
I tried for example this here:

```
searchControl.on('search_locationfound', function(e) {
map._layers.removeLayer(this._markerLoc);	
	});
	map.addControl(searchControl);
```

Also a lot of different stuff either. No positiv result!

**Comment by stefanocudini** [comment]
use option: *marker: false*

https://github.com/stefanocudini/leaflet-search/blob/master/examples/geojson-layer.html#L48

**Comment by kaio328** [comment]
Thanks for your response! I think u got me wrong: im not looking for a way to not show the marker when a location is found but for a way to hide it/remove it when its displayed on the map via my button.
