### ISSUE TITLE
Get searched marker title

### ISSUE THREAD

**Issue by marielouiese** [stefanocudini/leaflet-search#153]
First of all: I love your plugin! 
But how can I find the title that was just searched for? I'd like to set a variable to the string/marker title that was searched for so I can change the searched marker's opacity, highlighting the search result.

**Comment by stefanocudini** [comment]
Hi @marielouiese 

For many questions is more useful read directly source code and my comments inside it (yes writing explicit docs is very boring for me x_x).
About it the plugin is equipped with 3 events:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L63
*locationfound* return an event object contains latlng, title and layer(object found in the map for example the searched marker).

**Comment by jlengrand** [comment]
@stefanocudini Hey there, 

Care to indicate why you reopened the issue?

**Comment by stefanocudini** [comment]
?
