### ISSUE TITLE
Doesn't work when pasting into search field

### ISSUE THREAD

**Issue by tomchadwin** [stefanocudini/leaflet-search#154]
Is the search being triggered when pasting into the search field instead of manually typing?

**Comment by rwoodnz** [comment]
@stefanocudini 
Thanks very much for fixing this as we are one of those that have just been living with it. That's us with reference 'Search doesn't work when pasting data into search field #39'

An initial attempt to upgrade our module from Version 2.7.2 I found will impact our UI. A line appears above the box and the box is increased in size from 18 to 22. From commit 'update for leaflet 1.3.0, restyle' - f6ebac21774aeac953d3552dd667a6230f14617c

We are using mapbox.js 3.3.1 (looks like latest). I am assuming it is mapbox that is giving us Leaflet 1.0.2 as I can't see any specific inclusion of leaflet itself. In your knowledge is this older version of leaflet likely to be an issue in using leaflet-search 2.9.7. Besides those visual things, which I can mitigate with styles?
