### ISSUE TITLE
Is it possible to combined nominatim search with existing layers?

### ISSUE THREAD

**Issue by yoieh** [stefanocudini/leaflet-search#155]
I have renderad markers in a layer shown below:

```
var markersData = {...}

var searchLayer = L.geoJSON(markersData, {
  pointToLayer: function (feature, latlng) {
    return L.marker(latlng, {icon: newIcon(feature.properties.icon)});
  },
  onEachFeature: function (feature, layer) {
    layer.bindPopup(feature.properties.name);
  }
});
  markers.addLayer(searchLayer);
  map.fitBounds(markers.getBounds());

var controlSearch = new L.Control.Search({
  position:'topleft',
  layer: markers,
  initial: false,
  zoom: 12
 });

map.addControl(controlSearch);
```
My by goal is to add more searchable layers as shown in [multiple-layers](https://github.com/stefanocudini/leaflet-search/blob/master/examples/multiple-layers.html). This is easy and will work fine.

Now then i want to add [nominatim ](https://github.com/stefanocudini/leaflet-search/blob/master/examples/nominatim.html) search to the leaflet-search control to with out adding another input field. Is this possible or not?

I have tried the [ajax-jquery](https://github.com/stefanocudini/leaflet-search/blob/master/examples/ajax-jquery.html) example to but dont know if i cant get it to work with both input data from nominatim over ajax and my existing layers.

**Comment by stefanocudini** [comment]
Yes you can!
Use *sourceData* callback for search data by remote source using jQuery merge results in other layers and return these to callResponse(...)
https://github.com/stefanocudini/leaflet-search/blob/689c3deb30f1138d5e2a8a27610b6daf00df87d6/examples/custom-source-data.html#L60
