### ISSUE TITLE
Search not working when using clusterOptions

### ISSUE THREAD

**Issue by jp1312** [stefanocudini/leaflet-search#156]
Hi,

I've been trying the search functionality and it is not working when I add a cluster option in the addCircleMarkers(). Following the example on RPub, adding clusterOption the search does not work anymore for me. 

```
cities <- read.csv(textConnection("
City,Lat,Long,Pop
Boston,42.3601,-71.0589,645966
Hartford,41.7627,-72.6743,125017
New York City,40.7127,-74.0059,8406000
Philadelphia,39.9500,-75.1667,1553000
Pittsburgh,40.4397,-79.9764,305841
Providence,41.8236,-71.4222,177994
"))

leaflet(cities) %>% addTiles() %>%
  addCircleMarkers(lng = ~Long, lat = ~Lat, weight = 1, fillOpacity=0.5,
                   radius = ~sqrt(Pop)/50 , popup = ~City, label=~City, group ='cities',
                   clusterOptions = markerClusterOptions(maxClusterRadius=35)) %>%
  addSearchMarker(
    targetGroup = 'cities',
    options = searchMarkersOptions(zoom=12, openPopup = TRUE))

```

**Comment by BilboBaagins** [comment]
I had the same problem but ended up creating a bit of a work-around [here](https://github.com/bhaskarvk/leaflet.extras/issues/65) if you're interested. 

You basically add your markers twice (once clustered and once not clustered). You hide the non-clustered markers so they're not visible on the map and make them searchable. 

Its not great but it does the job.
