### ISSUE TITLE
autoType = false not working

### ISSUE THREAD

**Issue by narendrasinghrathore** [stefanocudini/leaflet-search#157]
set autoType = false not working. I am trying to disable auto search when min length is valid.

Just search when press enter key or when click on search icon.

But not working, please share demo if possible

**Comment by narendrasinghrathore** [comment]
@stefanocudini Can you help on this?
Thanks!

**Comment by stefanocudini** [comment]
Hi @narendrasinghrathore 
From version 2.7.2 to disable tooltip results you can use option: `tooltipLimit: 0` or `tooltipLimit: false`

**Comment by narendrasinghrathore** [comment]
@stefanocudini  It doesn't work.
![image](https://cloud.githubusercontent.com/assets/4208015/24824938/bdb8b63c-1c32-11e7-9418-170296540fcd.png)

**Comment by narendrasinghrathore** [comment]
@stefanocudini i need to disable search on TextChange. 
seet autoType = false or tooltipLimit: 0 or tooltipLimit: false 
Doesn't seems to work. 

Also i need to bind the click functionality to search icon.
Please let me know,
Thanks!

**Comment by narendrasinghrathore** [comment]
@stefanocudini 
![image](https://cloud.githubusercontent.com/assets/4208015/24825075/c282d33a-1c34-11e7-8c81-ae28d38e1617.png)
![image](https://cloud.githubusercontent.com/assets/4208015/24825078/d2b838e4-1c34-11e7-8acc-1404f492d88a.png)
![image](https://cloud.githubusercontent.com/assets/4208015/24825083/db69b8b4-1c34-11e7-96cd-06b5a628106c.png)

**Comment by narendrasinghrathore** [comment]
@stefanocudini Hi buddy, any update  ?

**Comment by stefanocudini** [comment]
Here work

https://jsfiddle.net/r2LLpLcb/2/

**Comment by narendrasinghrathore** [comment]
@stefanocudini 
by set tooltipLimit: 0 , just don't show the result. 
But keyup event is still working.
**I want to stop the function binded on keyup event.**
Let me know, if it's still not clear.
https://jsfiddle.net/r2LLpLcb/2/

**Comment by stefanocudini** [comment]
This can't be done because requires changes to the core of code and I do not see the general use case

**Comment by narendrasinghrathore** [comment]
@stefanocudini , We can set this optional by passing true/false at initialization. **I am happy to implement that functionality**. Let me know if i can **contribute**.
**Thanks!**
