### ISSUE TITLE
Is this project deprecated? How can we contribute

### ISSUE THREAD

**Issue by jlengrand** [stefanocudini/leaflet-search#159]
Hi there, 

I see that this project has 47 issues open, and 1 Pull Request that has been opened in January.
Most of the issues and Pull Requests do not see any answers from the creator of this library.

At the same time, I see that the project still seems alive, since the last commit dates from 5 days ago. 

What is the status of this project? IS there contribution guidelines? If you do not have enough time to dedicate to the project @stefanocudini , how can we help you?

Thanks!

**Comment by stefanocudini** [comment]
Hi @jlengrand 

This project is Active!

For contributing anyone can solve issues or implement things listed insiste TODO file:
https://github.com/stefanocudini/leaflet-search/blob/master/TODO

Or search //TODO comments inside the main javascript source code:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L35

Many people have already contributed with forks and tips
https://github.com/stefanocudini/leaflet-search/pulls?q=is%3Apr+is%3Aclosed

The pull requests that generate conflicts will not be considered, for example this last:
https://github.com/stefanocudini/leaflet-search/pull/101
