### ISSUE TITLE
leaflet-search + leaflet-markercluster

### ISSUE THREAD

**Issue by jhpoosthoek** [stefanocudini/leaflet-search#166]
Hi, I would like to use leaflet-search alongside https://github.com/Leaflet/Leaflet.markercluster/

This doesn't immediately work. Could you maybe give me a heads up on how to get it working?

Thanks!

**Comment by bhaskarvk** [comment]
The latest commit should work for markercluster too as it supports searching groups recursively.

**Comment by jhpoosthoek** [comment]
Thanks! I can't immediately figure out how the recursive search works. Maybe we could work together to make a little example for on your http://labs.easyblog.it/maps/leaflet-search/ ?

**Comment by stefanocudini** [comment]
@bhaskarvk searching groups recursively.. but what type of group?

**Comment by bhaskarvk** [comment]
Any instance of L.LayerGroup or L.FeatureGroup or L.GeoJSON can be recursively searched by the PR that you merged a while ago.

**Comment by jhpoosthoek** [comment]
Hi @JackNL85, no indeed, I didn't get it to work yet. It's still on my list to search further for a solution but didn't find time yet. @bhaskarvk could you maybe help out here?

**Comment by knaggs** [comment]
I have the mobile example working with Markercluster, but struggling on something else. Trying to add an event listener that is triggered when a search location is found. This is not working..

window.addEventListener("search:locationfound", showresults);
