### ISSUE TITLE
L.Control.Search isn't visible

### ISSUE THREAD

**Issue by d1m1tur** [stefanocudini/leaflet-search#169]
I add a control search for my geojson layer at topleft. In the DOM i can see it, and it says that the element is 0x0. I can remove the display:hidden for the input and its working like it should, but the icon for clicking is missing.

![screenshot_19](https://user-images.githubusercontent.com/8821686/28492809-cc538496-6f12-11e7-882b-9cb84a276834.png)
![screenshot_15](https://user-images.githubusercontent.com/8821686/28492808-cc532866-6f12-11e7-853e-72cba8c9c4bb.png)

The first images shows how it looks when i load the site.
In the second i have removed the hidden from the input.

**Comment by StefanBrand** [comment]
@d1m1tur Did you solve your issue?

**Comment by SuibianP** [comment]
@d1m1tur @StefanBrand Sorry for digging this up but I am facing exactly the same problem... Any suggestions or insights?
