### ISSUE TITLE
Ajax fragmented search 

### ISSUE THREAD

**Issue by Effectiva** [stefanocudini/leaflet-search#172]
Hi,

Firstly, thank you for the great add on.

I've created an ajax search function & when I search on the 'haa' I get the following results in console:
`[{"loc":[48.1618528,12.179467],"title":"Haag in Oberbayern (DE)"},{"loc":[52.0704978,4.3006999],"title":"Den Haag (NL)"},{"loc":[48.1850529,13.6413273],"title":"Haag am Hausruck (AT)"}]`

But in leaflet search I only get the results 'Haag in Oberbayern (DE)' & Haag am Hausruck (AT)?
Is there an option to activate a fragmented search so 'Den Haag (NL)' is also shown?

**Comment by Effectiva** [comment]
These lines code broke caused the bug:
`//TODO refact!
				//if(that.options.sourceData)
				//	records = that._filterData( that._input.value, that._recordsCache );
				//else`

**Comment by stefanocudini** [comment]
set *initial* to false:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L72

**Comment by Effectiva** [comment]
Hi,

I tried the change, but it doesn't work... :(

Kind regards,
Alco
