### ISSUE TITLE
search location by google geocoding not working perfectly

### ISSUE THREAD

**Issue by dramaking** [stefanocudini/leaflet-search#176]
If you go to [this page](http://labs.easyblog.it/maps/leaflet-search/examples/geocoding-google.html), type something and hit the enter key (or submit button) immediately after that, two problems will show up:
1. You get the error:
```
Uncaught TypeError: Cannot read property 'classList' of undefined
    at Object.pt [as addClass] (DomUtil.js:117)
    at e._handleArrowSelect (leaflet-search.js:794)
    at e._handleKeypress (leaflet-search.js:671)
    at HTMLInputElement.r (DomEvent.js:81)
```
which I believe has something to do with this function in the source code:
```
_handleKeypress: function (e) {	//run _input keyup event
		var self = this;

		switch(e.keyCode)
		{
			case 27://Esc
				this.collapse();
			break;
			case 13://Enter
				if(this._countertips == 1 || (this.options.firstTipSubmit && this._countertips > 0))
          if(this._tooltip.currentSelection == -1)
					  this._handleArrowSelect(1);
				this._handleSubmit();	//do search
```
_handleArrowSelect is called when results haven't been returned from google geocoder

2. When it is still fetching results from google geocoder(with the spinner showing up), "Location not found" shows up. It should wait until the results are returned from geocoder

**Comment by stefanocudini** [comment]
@dramaking you should indicate what words you type in the input search? because for more place it work

**Comment by dramaking** [comment]
@stefanocudini The first problem is pretty random, I typed "auckland" or "wellington", and hit the "enter" key really fast after that. Sometimes the error shows up, sometimes it doesn't.

The second problem always exists

**Comment by stefanocudini** [comment]
to fix a bug must be reproducible
