### ISSUE TITLE
Error within Leaflet v1.2.0

### ISSUE THREAD

**Issue by ppete2** [stefanocudini/leaflet-search#177]
At least if this plugin is used within Leaflet 1.2.0 it isn't working anymore. If entering a town to search for, the Browser console writes an error wihtin lines 32 and 76 of the plugin:

Firefox: _"TypeError: this.options is undefined"_
Chrome: _"Uncaught TypeError: Cannot read property 'propertyName' of undefined"_

**Comment by stefanocudini** [comment]
ok... in the [README](https://github.com/stefanocudini/leaflet-search/blob/master/README.md) is indicated the leafleat current supported. 0.7.7 and 1.1.0
