### ISSUE TITLE
Search result is not updated if backspace key is pressed

### ISSUE THREAD

**Issue by asllad** [stefanocudini/leaflet-search#178]
The search result is not updated if the backspace key is pressed.
Easy testable in example:
http://labs.easyblog.it/maps/leaflet-search/examples/methods.html
Enter "arkb" in the map search field. 
You will see only "darkblue".
After press backspace key in the search field you only see "ark".
You will see again only "darkblue"!
Press again the backspace and then press "k" give the correct result "darkblue, darkred, darkgray"

**Comment by stefanocudini** [comment]
when I type backspace and cancel the last char.. 'b' in my test it work!  show immediately darkblue, darkred, darkgray

**Comment by neogeomat** [comment]
Not Working in [demo](https://opengeo.tech/maps/leaflet-search/examples/simple.html). type 'bla' and you see 'black'. Press backspace to make 'bl', only 'black; is available. remove 'l' as well and then type 'l' expected result appears 
black
blue
darkblue
dodgerblue
royalblue
skyblue

Tested in latest firefox, edge, brave

**Comment by neogeomat** [comment]
Looks like Backspae is not handled. https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L706

**Comment by neogeomat** [comment]
Commenting out that line fixed the issue.
`// case  8://Backspace`

**Comment by stefanocudini** [comment]
solved from leaflet-search@3.0.9
