### ISSUE TITLE
Geocode Nominatim (this.opions undefined (line 469))

### ISSUE THREAD

**Issue by malde11** [stefanocudini/leaflet-search#180]
I changed the version of the leaflet-search plugin and get this message in the console:
**TypeError: this.options is undefined (line 469)**

Autocomplete is not working. Same error on your example site.

I see you are working on it the past days. Hope you can fix it.

Great work, thanks.

**Comment by jieter** [comment]
Just downgraded to 2.3.5 to make this work again.

**Comment by malde11** [comment]
Sorry, I am a beginner and really new to this git thing. I have downloaded the newest .zip-file from this repository. I wanted to get rid of this error message in the console:

**Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead.**

Now, I updated(leaflet 1.2.0 and the newest zip-file from leaflet-search, I guess it is the master branch) everything and got this message in the first post.

Is the newest zip-file the 2.3.6 version?
Do I need git or npm to get the 2.3.5 version? I found under releases only the 2.3.0 version.
I have installed git now, but do not know the right command, to get this 2.3.5 version. Is it possible with git or do I need npm?

Thanks for the help. :sweat_smile:
