### ISSUE TITLE
getBounds error with CircleMarkers

### ISSUE THREAD

**Issue by bplewe** [stefanocudini/leaflet-search#181]
I am trying to search through a set of CircleMarkers; recently it started throwing an error whenever it tried to search:
layer.getBounds is not a function on line 577
I believe this is due to the recent change in Leaflet that switches the inheritance of Circle and CircleMarker, so CircleMarker no longer has a getBounds function.

On line 568, I changed the if to else if, which solves the problem (don't know yet if it introduces others).

**Comment by mebloscian** [comment]
I've got simillar problem here. Just changed line 561 to:
loc = layer.getLatLng();

**Comment by stefanocudini** [comment]
yes you have right!

**Comment by stefanocudini** [comment]
solved from version 2.9.0
