### ISSUE TITLE
Src/leaflet-search-geocoder.js not supported

### ISSUE THREAD

**Issue by tger** [stefanocudini/leaflet-search#184]
The code in _src/leaflet-search-geocoder.js_ is obviously half-baked. I think the approach is good (having a predefined set of geocoders that the user can include and choose from). I have a prototype working of this (each geocoder has dedicated url and formatData properties), but I believe that some code in _leaflet-search.js_ needs to modified. (Or internal methods such as __getUrl_ and __fillRecordsCache_ need to be overridden, which is not so nice).

Any plans and ideas on how to best support this?

**Comment by stefanocudini** [comment]
I don't have again a elegant solution for this...

**Comment by stefanocudini** [comment]
@tger you have some updates?

**Comment by tger** [comment]
OK, I will see if I can find time to upstream this. We have this running in production with an option to switch geocoder backend at runtime (if one geocoder goes down we can switch to another one without a rebuild which was desirable for us but perhaps not so useful in the general case).
