### ISSUE TITLE
Don't display markers when in used with Leaflet.Markercluster

### ISSUE THREAD

**Issue by kirantpatil** [stefanocudini/leaflet-search#185]
Hi,

I am using leaflet-search with Leaflet.Markercluster.

It works fine but, it displays marker icons as soon as map loads. 

Please find the below screenshot. The cluster has 4 markers in it.

How to disable it ?

Edit: We would like to display markers only when we click on the cluster, which is default behaviour of Leaflet.Markercluster.

Thanks,
Kiran.

![screenshot-2017-12-11 containermon](https://user-images.githubusercontent.com/1178055/33819316-ce4929be-de6f-11e7-8415-9d42157f1049.png)

**Comment by kirantpatil** [comment]
We would like to display marker/s only when we search it and when we click on the cluster.

**Comment by stefanocudini** [comment]
its the same of #188

**Comment by xiankai** [comment]
@kirantpatil I used to have a similar problem, until I realized that I was adding the layer containing the markers, NOT the markerclusterer layer. 

As a result 2 separate layers were added, the one with all markers in the search, and the markerclusterer layer itself.

Adding the markerclusterer layer itself to the search control "removed" the duplicate markers.

Hope that helps!
