### ISSUE TITLE
search and get marker details

### ISSUE THREAD

**Issue by kirantpatil** [stefanocudini/leaflet-search#187]
Hi,

I would like to search and get the marker details from its properties, tooltips ..., to be shown on the browser.

Please help me how to do.

Thanks.

**Comment by kirantpatil** [comment]
Ex: I have altered the outside.html example and find the below screenshot.

The search values are from the Marker object content like title, tooltips and ...

![screenshot-2017-12-11 screenshot](https://user-images.githubusercontent.com/1178055/33825170-c4a66e5a-de86-11e7-89db-982741c78c21.png)

**Comment by stefanocudini** [comment]
http://leafletjs.com/reference-1.2.0.html#marker
I wish you good study
