### ISSUE TITLE
zoominto cluster if marker found in cluster

### ISSUE THREAD

**Issue by kirantpatil** [stefanocudini/leaflet-search#188]
Hi,

Right now when I search, map is not zoominto the cluster to show that marker but only points to the cluster.

How to achieve it ?

Thanks.

**Comment by stefanocudini** [comment]
try to set a higher value of zoom option, ore set another value for zoom in makrer cluster.

https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L70
