### ISSUE TITLE
How to use "buildTip" without geojson

### ISSUE THREAD

**Issue by idenchev** [stefanocudini/leaflet-search#193]
Hello Stefano,

Your work with Leaflet-Search is really amazing :) Thank you so much!

For some time I am struggling to find out how to setup buildTip option when the input is not a geoJSON object, but a simple .js file.

In short:

1. I am loading multiple .js fils with following 2 formats:

```javascript
var sites = [
{"loc":[42.65158349,23.40341614], "ID":"1010", "Type":"Site"},
{"loc":[42.69877797,23.34825435], "ID":"1012", "Type":"Site"},
{"loc":[42.71530326,23.24433912], "ID":"1014", "Type":"Site"},
```
and
```javascript
var cells_gsm = [
{"loc":[42.69340232,23.36178137], "ID":"100819","azim":130, "Type":"Cell"},
{"loc":[42.69340232,23.36178137], "ID":"100829","azim":210, "Type":"Cell"},
{"loc":[42.69340232,23.36178137], "ID":"100839","azim":320, "Type":"Cell"},
```
2. Then I build circles and semiCircles with:
```javascript
for(i in cells_gsm) {
	var title = cells_gsm[i].ID,
	loc = cells_gsm[i].loc,
	azim = cells_gsm[i].azim,
	object = cells_gsm[i].Type,
	marker = new L.semiCircle(new L.latLng(loc), {radius: radinit+240, color: 'blue', weight: 1, title: title, pane: "gsmPane"} ).setDirection(azim, 68).bindPopup(object+': '+ title );

	layerGSM.addLayer(marker);
}

for(i in sites) {
	var title = sites[i].ID,
	loc = sites[i].loc,
	object = sites[i].Type,
	marker = new L.circle(new L.latLng(loc), {radius: radsiteinit+50,color: 'gold', weight: 3, title: title, pane: "sitePane"} ).bindPopup(object+': '+ title );

	layerSites.addLayer(marker);
}
```
3. Then I am building a layerGroup which consists of multiple layerGroups:
```javascript
var layerAll = L.layerGroup([layerUMTS1,layerUMTS2,layerUMTS9,layerGSM,layerSites])
```
4. Finally I am calling your serach feature with:
```javascript
var controlSearch = new L.Control.Search({
	position:'topright',
	layer: layerAll,
	initial: false,
	hideMarkerOnCollapse: true,
	zoom: 17
	buildTip: function(text, val) {
	var type = ??????;
	return '<a href="#" class="'+type+'">'+text+'<b>'+type+'</b></a>';
	}
});
```

The searched value is "ID" from point 1. I would like to have "Type" shown as buildTip (depending on the inputs it should be "Site" or "Cell"):
```javascript
{"loc":[42.69340232,23.36178137], "ID":"100819","azim":130, "Type":"Cell"},
```
Unfortunately I cannot get it work. I studied your example for multiple layers, but this example is when one has geoJSON object. What should I put here on the place of question marks - var type = ??????;?

Otherwise seraching itself works like charm :)

Thank you in advance!

Best Regards,
Ivaylo Denchev

**Comment by FoTo50** [comment]
I solved it in my case following:

I added the markers per layer group like
```var marker = L.marker(latlng, {title: somecooltitle, icon: coolicon, className:"coolmarkerclass"}).bindPopup(popupContent).addTo(layergroup);```

in the buildTip function, I then could access className like:

```return '<a href="#" class="'+val.layer.options.className+'">'+text+'</a>';```

Hope this helps

@stefano: this search feature simply rocks :)

**Comment by stefanocudini** [comment]
@FoTo50 great solution!

@idenchev use it!
