### ISSUE TITLE
Conflict w/Leaflet Dialog

### ISSUE THREAD

**Issue by Avatar690** [stefanocudini/leaflet-search#195]
Trying to use both, if I load dialog first I get a constructor error.  If I load search first, I get a inithook error... likely a similarly named function.  Is there a resolution to this?

https://github.com/NBTSolutions/Leaflet.Dialog (for Dialog plugin)

**Comment by stefanocudini** [comment]
functions having same name il impossible because each plugins has his namespace

**Comment by stefanocudini** [comment]
@Avatar690 try to change position option in each plugins

**Comment by Avatar690** [comment]
Gave it a go.  Still get the 'L.Control.Search is not a constructor' when initializing.

**Comment by Avatar690** [comment]
Likely a leaflet 1.3 issue... as that is the version I am on.  I stripped it down to just leaflet and leaflet search and still have the issue.  Just FYI.
