### ISSUE TITLE
getBounds does not work for L.Path in leaflet.js v1.3.1

### ISSUE THREAD

**Issue by schloerke** [stefanocudini/leaflet-search#196]
http://leafletjs.com/reference-1.3.0.html#path Path methods do not include `.getBounds()`. So items like CircleMarker (extends Path) do not work, but Circles or Polylines have their own method.

bhaskarvk/leaflet.extras#135

**Comment by stefanocudini** [comment]
solved from version 2.9.0

**Comment by schloerke** [comment]
@stefanocudini This issue is still not fixed in 2.9.0.  

https://github.com/stefanocudini/leaflet-search/commit/91bcce1a2b047bfc01791f32572ab9e3f2ddcd8c#diff-8f0fc9abc510b9969a094a4f133554c9R569 still contains a check against `L.Path`.  `L.Path` objects do not have a `layer.getBounds()` method.
