### ISSUE TITLE
multiple search boxes overlap

### ISSUE THREAD

**Issue by astomas** [stefanocudini/leaflet-search#197]
When adding multiple search boxes, the results of the top one are partially hidden by the empty ones below (see capture). Is it possible to collapse the other search boxes while one is opened?
![overlap search](https://user-images.githubusercontent.com/4425097/39526296-a359f08e-4e1e-11e8-8e69-5b088d6d9f20.PNG)

**Comment by stefanocudini** [comment]
Multiple search boxes are one thing that confuses the user experience... should not be there :-/

**Comment by albabrobia** [comment]
looking for a solution related to this issue: is it possible to **mix-combine** two different search engines (e.g. **search by feature** and s**earch by location**) into the same search box by using leaflet-search.js? If yes, where I can find an example? THANK YOU

**Comment by stefanocudini** [comment]
you can combine mutiple search ways in the same callData function

**Comment by mramizal** [comment]
could you give a sample code on this.. thanks

**Comment by stefanocudini** [comment]
@mramizal here you can concat yours double data in the same object before pass to callResponse
https://github.com/stefanocudini/leaflet-search/blob/master/examples/custom-source-data.html#L62
