### ISSUE TITLE
More information than available in search:locationfound?

### ISSUE THREAD

**Issue by ThomasDaheim** [stefanocudini/leaflet-search#199]
Hi Stefan,

thanks a lot for your plugin! After getting it to work in my map I came up with the following:

- In my function for search:locationfound the "text" attribute of the event is always empty, whereas latlng is filled. Any ideas how this could come about?

- I would be interested in receiving all the information as available in the tooltip (or even better, the unformated json response...) Is there any way to achieve this? I have seen some callback functions available in options but I'm not sure which (if any) would do the trick.

Thanks and regards,
Thomas

**Comment by stefanocudini** [comment]
lokk at here for a similar use case:
http://labs.easyblog.it/maps/leaflet-search/examples/geojson-layer.html

```javascript
 searchControl.on('search:locationfound', function(e) {
   console.log('search:locationfound text', e.text);
 });
```

**Comment by stefanocudini** [comment]
hi Thomas,
in my examples the code work always.. may be you case study is broken, sholde
you should share the code of your case to understand something

**Comment by ThomasDaheim** [comment]
Hi Stefan,

sorry I didn't have time to try and compile a simple sample. And now I'm heading for vacations :-) Will try and have a look at it when I'm back...
