### ISSUE TITLE
The map is cut when I did search  bug

### ISSUE THREAD

**Issue by hmarina** [stefanocudini/leaflet-search#200]
Hello every one I am using this plugin but when I did a search in the map is cut and no refresh. It is happening in mobile devices

error o bug
http://190.79.194.201/images/image.png

map.addControl( new L.Control.Search({
		url: 'http://nominatim.openstreetmap.org/search?format=json&q={s}',
		jsonpParam: 'json_callback',
		propertyName: 'display_name',
		propertyLoc: ['lat','lon'],
		 //marker: L.circleMarker([0,0],{radius:30}),
		autoCollapse: true,
		autoType: false,
		minLength: 2
	}) );

**Comment by stefanocudini** [comment]
check the css is included in the page

**Comment by hmarina** [comment]
I check in my proyect and the css is include, the problem persiste
