### ISSUE TITLE
var data help how to convert it to post

### ISSUE THREAD

**Issue by blayanc** [stefanocudini/leaflet-search#202]
var data = [
	  [-41.31825,174.80768],
	  [-41.31606,174.80774],
	  [-41.31581,174.80777],
	  [-41.31115,174.80827],
	  [-41.30928,174.80835],
	  [-41.29127,174.83841],
	  [-41.33571,174.84846],
	  [-41.34268,174.82877]];

<?php
$query = mysql_query("SELECT * FROM $database ")or die(mysql_error());
while($row = mysql_fetch_array($query))
{
      $project_n = $row['project_n'];
      $lat = $row['lat'];
      $lon = $row['lon'];
      $location = $row['location'];
      $flora = $row['flora'];
      $housemod = $row['housemod'];
      $apprname = $row['apprname'];
      $lotper = $row['lotper'];
      $unitper = $row['unitper'];
      $remarks = $row['remarks'];
      $remarks2 = $row['remarks2'];
      $date_received = $row['date_received'];
      $rcn = $row['rcn'];
      $valunit = $row['valunit'];
      $link = $row['link'];
      $typeaccnt = $row['typeaccnt'];
    

 
	echo 'var data = [
    {"loc":[14.575330,121.102411], "title":"$project_n"}];';
     
 }
?>

**Comment by stefanocudini** [comment]
what?
