### ISSUE TITLE
Start leafletSearch without marker

### ISSUE THREAD

**Issue by Rickyc81** [stefanocudini/leaflet-search#203]
Hi, is possible to use leaflet search plug-in and start without marker on map? And show only the marker that is found. 
Thanks 
Riccardo

**Comment by Rickyc81** [comment]
Option marker: {false} ?

**Comment by knaggs** [comment]
I believe the mobile.html example does just this. You can use this example in a plain browser. Hope this helps.

**Comment by Rickyc81** [comment]
Oh, thanks.. i will'try It..
