### ISSUE TITLE
Error in calculating the maxWidth of the search field

### ISSUE THREAD

**Issue by nelsonmalo** [stefanocudini/leaflet-search#206]
Hi guys

Look this image:
![image](https://user-images.githubusercontent.com/33978725/45762078-7a82bb80-bc25-11e8-9d48-07057234ec57.png)

The search inputs has a very small width, because the plugin is not checking correctly the map width.
This happens when the map has the width 100%

 This is the current code:

	    var maxWidth;
		if (this._input.style.maxWidth !== this._map._container.offsetWidth) {
			maxWidth = L.DomUtil.getStyle(this._map._container, 'width');
			maxWidth = parseInt(maxWidth);
			 // other side margin + padding + width border + width search-button + width search-cancel
			maxWidth -= 10 + 20 + 1 + 30 + 22; 

			this._input.style.maxWidth = maxWidth.toString() + 'px';
		}

		

This is a new code:

	    var maxWidth;
		if (this._input.style.maxWidth !== this._map._container.offsetWidth) {
			maxWidth = L.DomUtil.getStyle(this._map._container, 'width');
                        if (maxWidth=="100%"){
                              maxWidth =this._map._container.offsetWidth;
                         }
                        maxWidth = parseInt(maxWidth);
			 // other side margin + padding + width border + width search-button + width search-cancel
			maxWidth -= 10 + 20 + 1 + 30 + 22; 

			this._input.style.maxWidth = maxWidth.toString() + 'px';
		}

If possible make fix to this issue in the next version.
Thank you

**Comment by stefanocudini** [comment]
may be this problema is caused from one of last merge here:
https://github.com/stefanocudini/leaflet-search/pull/205
@barretomateus did you check that it work before sending your PR?

@nelsonmalo could you send me a pull request for this change please? ;-)

**Comment by nelsonmalo** [comment]
@stefanocudini 
Of course I can, but as I'm a new member in Gitub and I don't know how to do that. 
Could you help me?

**Comment by barretomateus** [comment]
@stefanocudini 
Of course I did check, even because my projects with leaflet also has width set to 100% and it worked normally. I tested on Chrome 61 and Firefox 54

@nelsonmalo 
Which browser you are using?

**Comment by nelsonmalo** [comment]
@barretomateus ;)
![image](https://user-images.githubusercontent.com/33978725/45884083-c90d9280-bdaa-11e8-8245-75efea7f8cd8.png)

**Comment by stefanocudini** [comment]
@barretomateus I still have the latest version but it does not work :(

**Comment by barretomateus** [comment]
That is really strange, I will investigate it deeper and come back with more answers

**Comment by stefanocudini** [comment]
soved from version 2.8.6
