### ISSUE TITLE
No results displayed but there are results returned after 3 seconds

### ISSUE THREAD

**Issue by Sandbird** [stefanocudini/leaflet-search#208]
I am having a weird bug with an ajax search. I use the plugin to search for zip codes in a database. When i add a single zip code, everything is fine, but when i request a range of values (55000-55999), something that might take 2 more seconds of search in the db the search spinner stops, nothing is shown and then i see in the console the results come back from the database having the proper json format and all. Is there a timeout or something weird like that ? I just can't debug this.
This is how i initialize the plugin. First i check in which country the user has zoomed into so i cut down the db query by knowing the country ISO code. And of course i send that to the ajax request as well.

```javascript
function searchByAjax(text, callResponse)//callback for 3rd party ajax requests
{
  var latlngs = map.getCenter();
  var countryselected = '';
	var getc = $.ajax({ url:'https://api.mapbox.com/geocoding/v5/mapbox.places/'+latlngs.lng+','+latlngs.lat+'.json?access_token=xxxxxxxxx&types=country&limit=1',
     success: function(data){
     	if(data.features[0] != null){
      	countryselected = data.features[0].properties.short_code.toUpperCase();
    	}
     }
  });
	$.when(getc).done(function() {
		return $.ajax({
		  url: "zipselect/search/",
			type: 'GET',
			data: {'action': 'getone', q: text, c: countryselected},
			dataType: 'json',
			success: function(json) {
				callResponse(json);
			}
		});
	});
}
map.addControl( new L.Control.Search({
	sourceData: searchByAjax, 
	initial: false,
	position: 'topleft',
	propertyName: 'title',
	showOnly: 'zip',
	markerLocation: true,
	minLength: 3,
	marker: L.circleMarker([0,0],{radius:1})
}));
```
In my PHP page i break down the {q} request to see if it is a range search or not. Its basically the same SQL query, just brings more results or not.
```javascript
$req = $_GET['q'];
$pos = strpos($req, '-');
if ($pos === false) {
	$zip_code = "zipcode LIKE '".$req."%'";
}else{
	$break = explode('-', $req);
	$zip_code = "zipcode BETWEEN '".$break[0]."' AND '".$break[1]."' ";
}
```
Like i said both style of searches bring back the same formated results. I mean i could beta test that by searching for example 55421 or 55421-55421  to get the same results.
The only difference is with the single valued search the plugin waits for the ajax query to return results but when i do the range one the spinner stops after 2 seconds and on the 3rd the results come back from the ajax script.
Any ideas ?
Thanks

**Comment by Sandbird** [comment]
I am idiot, ....i just noticed this line here:
`text = text.replace(/[.*+?^${}()|[\]\\]/g, '');`
How can i allow - (minus) in the _defaultFilterData function..Regex was always my achilles heel :/

**Comment by Sandbird** [comment]
Set `initial: false` , problem solved.

**Comment by stefanocudini** [comment]
finally someone who helps me to close the issues :)
