### ISSUE TITLE
L.Control.Search is not a constructor 

### ISSUE THREAD

**Issue by pw17l008** [stefanocudini/leaflet-search#210]
Hi there!

So I am in the process of adding this to my Leaflet Angular App. I install the package with npm and also linked the require css and js files. Now when I tried to create the layer and add functionality i always get the error "L.Control.Search is not constructor ".

Below is my code:

    var markersLayer = new L.LayerGroup();
    map.addLayer(markersLayer);

    var controlSearch = new L.Control.Search({
      position:'topright',
      layer: markersLayer,
      initial: false,
      zoom: 12,
      marker: false
    });

    map.addControl( controlSearch );

your help is much appreciated! thank you!

**Comment by stefanocudini** [comment]
<script src="https://unpkg.com/leaflet@1.3.0/dist/leaflet.js"></script>
--
  | <script src="../src/leaflet-search.js"></script>

**Comment by jt196** [comment]
Ciao @stefanocudini - quick question:

```
    mymap.addControl(new L.Control.Search({
        url: 'https://nominatim.openstreetmap.org/search?format=json&q={s}',
        jsonpParam: 'json_callback',
        propertyName: 'display_name',
        propertyLoc: ['lat','lon'],
        markerLocation: true,
        autoType: false,
        autoCollapse: true,
        minLength: 2,
        zoom:16
    }));
```
Method works up to 2.9.7, then it breaks - giving me the 'Not a Constructor' error message. Should I stick with the older versions or is there a new method to replace this function on more recent versions. Using the UNPKG CDN version rather than NPM.

**Comment by stefanocudini** [comment]
solved from version 3.0.0

**Comment by jt196** [comment]
> @jt196 solved from version 3.0.0

OK I'll have a better look on upkg then for v3. Cheers!

**Comment by stefanocudini** [comment]
cheers my beer friend! ^_^

**Comment by dorzz02** [comment]
is this still working? i'm using v3.0.2 still having this error.

**Comment by gisupanalizy** [comment]
Not working for me as well..

**Comment by stefanocudini** [comment]
???

**Comment by ANDYAGUIRRE10** [comment]
Ciao @stefanocudini, grazie per aver condiviso il tuo lavoro!
Vorrei sapere se puoi aiutarmi con il mio problema. Ho scaricato il folder e l'ho lasciato dove si trova il mio index.
Questo é il mio codice:
Sotto leaflet ->   <link rel="stylesheet" href="repo_dev\leaflet-search-master\dist\leaflet-search.src.css"/>
Non uso questo ->  <script src="https://unpkg.com/leaflet@1.3.0/dist/leaflet.js"></script> <script src="../src/leaflet-search.js"></script> 
perche ho il mio GeoJson in Geoserver, allora questo é il mio codice sotto il mio GeoJson chiamato verso "fetch":
const searchControl = new L.Control.Search({
    layer: puentes
});
map.addControl(searchControl);  
Tante grazie!
