### ISSUE TITLE
resize event still called after control is removed from map

### ISSUE THREAD

**Issue by puggimer** [stefanocudini/leaflet-search#215]
If you remove the search control from the map, it still has the hook for the 'resize' event - this then throws an exception when the map is resized (because the map value on the control is null when it is not on the map).

Simple fix - remove the listener in the onRemove function for the search control
map.off({
    'resize': this._handleAutoresize
}, this);

**Comment by stefanocudini** [comment]
fixxed from versino 2.9.8
