### ISSUE TITLE
Nominatim demo broken - https url 

### ISSUE THREAD

**Issue by zbycz** [stefanocudini/leaflet-search#216]
Hi,

this page:
https://labs.easyblog.it/maps/leaflet-search/examples/geocoding-nominatim.html
Uses insecure http:// url for nominatim service which is rejected by browser.

Can you please fix the url to https://? or possibly just `//nominatim.openstreetmap.org...` :-)

**Comment by rmarzocchi84** [comment]
I use it with https://nominatim.openstreetmap.org/search? and I confirm that it works

**Comment by stefanocudini** [comment]
now it works for me!
