### ISSUE TITLE
combine mutiple search

### ISSUE THREAD

**Issue by mramizal** [stefanocudini/leaflet-search#219]
you can combine mutiple search ways in the same callData function

_Originally posted by @stefanocudini in https://github.com/stefanocudini/leaflet-search/issues/197#issuecomment-394620628_

i need to do searching both in url using openstreetmap and geojson layer data.
can anyone provide sample code for this.. thanks

**Comment by stefanocudini** [comment]
you can add this logic inside callData function that return a simple object
