### ISSUE TITLE
_handleArrowSelect function - uncaught reference (i) in for loop

### ISSUE THREAD

**Issue by Robc24** [stefanocudini/leaflet-search#221]
@stefanocudini 

When I do any search and try to use the arrow key to navigate the results i receive a reference exception:

`Uncaught ReferenceError: i is not defined`

This is triggered by the for loop on line 828 in **leaflet-search.src.js**.  i is an implicit global variable and in strict mode this will kick up an error:

`for (i=0; i<searchTips.length; i++)`

If you declare i then it fixes the error.  It becomes a local variable i.e:

`for (let i=0; i<searchTips.length; i++)`

Can this be updated in the package?

**Comment by Mathieu-DA** [comment]
I am facing the same issue.

**Comment by stefanocudini** [comment]
> @stefanocudini
> 
> When I do any search and try to use the arrow key to navigate the results i receive a reference exception:
> 
> `Uncaught ReferenceError: i is not defined`
> 
> This is triggered by the for loop on line 828 in **leaflet-search.src.js**. i is an implicit global variable and in strict mode this will kick up an error:
> 
> `for (i=0; i<searchTips.length; i++)`
> 
> If you declare i then it fixes the error. It becomes a local variable i.e:
> 
> `for (let i=0; i<searchTips.length; i++)`
> 
> Can this be updated in the package?

please send me a Pull Request.

**Comment by stefanocudini** [comment]
or if you want @Mathieu-DA

**Comment by Mathieu-DA** [comment]
@stefanocudini could this possibly be merged into V2.9.8 ?
V2.9.9 currently seems to be broken (#265)

**Comment by stefanocudini** [comment]
solved from version 3.0.0 published in npm

**Comment by jt196** [comment]
FYI @stefanocudini, I'm pretty new to npm, so I don't know how long it takes for sync to happen between your code and npm. I did a leaflet-search install on npm today and the code isn't updated. I'm assuming I'll just have to wait for this to happen - unless you didn't make the change yet.

**Comment by stefanocudini** [comment]
https://www.npmjs.com/package/leaflet-search/v/3.0.0

https://github.com/stefanocudini/leaflet-search/commits/v3.0.0

**Comment by jt196** [comment]
Dude, just updated to the 3.0.1 version and double checked the GitHub code, the line `for (i=0; i<searchTips.length; i++)` is still [there](https://github.com/stefanocudini/leaflet-search/blob/6dd2e396958e619409f65123a4cd6d766e093bb5/dist/leaflet-search.src.js#L828), if you replace it with `for (let i=0; i<searchTips.length; i++)` as @Robc24 mentioned, the up/down arrow key function works again.
