### ISSUE TITLE
add feature popup to marker when searched using the ajax search example https://labs.easyblog.it/maps/leaflet-search/examples/ajax.html 

### ISSUE THREAD

**Issue by lisas1** [stefanocudini/leaflet-search#227]
hie..am trying to add a popup on search location found using the ajax search method from leaflet search example...any idea how i can do that...thanks

**Comment by stefanocudini** [comment]
You need to use events.. look at this example for reference:
https://github.com/stefanocudini/leaflet-search/blob/master/examples/geojson-layer.html

```javascript
var featuresLayer = new L.GeoJSON(data, {
	style: function(feature) {
		return {color: feature.properties.color };
	},
	onEachFeature: function(feature, marker) {
//HERE YOU DEFINE A POPUP FOR EACH FEATURE
		marker.bindPopup('<h4 style="color:'+feature.properties.color+'">'+ feature.properties.name +'</h4>');
	}
});
map.addLayer(featuresLayer);

var searchControl = new L.Control.Search({
	layer: featuresLayer
});

//HERE EVENT FIRED WHEN LOCATION IS FOUND... OPEN YOUR POPUP!
searchControl.on('search:locationfound', function(e) {
	if(e.layer._popup)
		e.layer.openPopup();
});

```

**Comment by lisas1** [comment]
thank you..in the case of using point features its showing markers before searching for the location..how should i do it

**Comment by lisas1** [comment]
thank you..however am trying to search for point features and its displaying  marker before searching for the location..how do i do it

**Comment by stefanocudini** [comment]
https://leafletjs.com/reference-1.5.0.html#popup

this is something that concerns the Leaflet library and not the leaflet-search plugin in particular.
I'm telling you to study the LeafletJS documentation, which is very simple
