### ISSUE TITLE
cannot search for point features

### ISSUE THREAD

**Issue by lisas1** [stefanocudini/leaflet-search#228]
thank you so much however i cannot search for point features..the markers are being displayed before i search for the location...how do i display only the searched marker

You need to use events.. look at this example for reference:
https://github.com/stefanocudini/leaflet-search/blob/master/examples/geojson-layer.html

```javascript
var featuresLayer = new L.GeoJSON(data, {
	style: function(feature) {
		return {color: feature.properties.color };
	},
	onEachFeature: function(feature, marker) {
//HERE YOU DEFINE A POPUP FOR EACH FEATURE
		marker.bindPopup('<h4 style="color:'+feature.properties.color+'">'+ feature.properties.name +'</h4>');
	}
});
map.addLayer(featuresLayer);

var searchControl = new L.Control.Search({
	layer: featuresLayer
});

//HERE EVENT FIRED WHEN LOCATION IS FOUND... OPEN YOUR POPUP!
searchControl.on('search:locationfound', function(e) {
	if(e.layer._popup)
		e.layer.openPopup();
});

```

_Originally posted by @stefanocudini in https://github.com/stefanocudini/leaflet-search/issues/227#issuecomment-493406729_

**Comment by stefanocudini** [comment]
https://leafletjs.com/reference-1.5.0.html#popup

this is something that concerns the Leaflet library and not the leaflet-search plugin in particular.
I'm telling you to study the LeafletJS documentation, which is very simple

**Comment by lisas1** [comment]
thank you so much
