### ISSUE TITLE
Documentation question: what is `markerLocation: true`?

### ISSUE THREAD

**Issue by chx** [stefanocudini/leaflet-search#255]
I see it here and there eg. https://labs.easyblog.it/maps/leaflet-search/examples/ajax-jquery.html but searching the repo and Google both reveals me nothing what the purpose of this property is. Thanks for the great library!

**Comment by just-Addict** [comment]
`markerLocation` is also referred to in his FIXME list in the code itself and it being mentioned in conjunction with autoCollapse I'm guessing this is a leftover from a refactoring action. Since that property doesn't exist I can only guess that the correct property name is now `movetoLocation`.
