### ISSUE TITLE
sourceData functionaliry broken (regression from last commit 9875037eda0986c110519fe820b8f10ca6e82c81)

### ISSUE THREAD

**Issue by jbiermann** [stefanocudini/leaflet-search#266]
I have noticed that the sourceData option is not working. You can see that the example [custom source data](https://github.com/stefanocudini/leaflet-search/blob/master/examples/custom-source-data.html) is broken.

The reason is that in the function _fillRecordsCache the if clause has been changed to  "if(this._layer)" during this commit: https://github.com/stefanocudini/leaflet-search/commit/9875037eda0986c110519fe820b8f10ca6e82c81

This brakes the sourceData functionality since the _layer variable is initialised during [Line 124](https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L124). It is either the supplied layer or if the layer is null, the layer is a new empty layer. Now the changed if in the _fillRecordsCache function is always true, since the _layer variable is always an object.

**Comment by ppete2** [comment]
see also #265

**Comment by stefanocudini** [comment]
solved from vedsion 3.0.0 published in npm
