### ISSUE TITLE
test of this._layer makes no sense, it should test this.options.layer.

### ISSUE THREAD

**Issue by easz** [stefanocudini/leaflet-search#273]
At the current code

this._layer is as always initiated. 
https://github.com/stefanocudini/leaflet-search/blob/b3868be16c9fa78c318d2ff485c047714034d826/src/leaflet-search.js#L124

and it would make the condition test useless.
https://github.com/stefanocudini/leaflet-search/blob/b3868be16c9fa78c318d2ff485c047714034d826/src/leaflet-search.js#L755

is it for any reason?
In tag 2.9.8 the condition is tested on `this.options.layer.` which should be the correct one.

**Comment by easz** [comment]
duplicated with #265

**Comment by stefanocudini** [comment]
solved from version 3.0.0 published in npm

**Comment by syyyr** [comment]
Testing for `this.options.layer` means that you must supply a layer in the options at the creation of the search control, otherwise layer search is completely disabled, even if you set the layer later via `setLayer()`.
