### ISSUE TITLE
Is leaflet-search still maintained?

### ISSUE THREAD

**Issue by ppete2** [stefanocudini/leaflet-search#278]
For several months this useful plugin is not working anymore with it's latest codebase. There are several opened issues #265, #270, #266 regarding this issue, also a PR #272 has been submitted. Unfortunately all unanswered by Stefan. 
Since about 1 week also the demo site [https://labs.easyblog.it/maps/leaflet-search/](https://labs.easyblog.it/maps/leaflet-search/) is down #276, and no reaction of Stefan too.

Is this plugin gonna be maintained any longer, or should a fork be created?

**Comment by stefanocudini** [comment]
solved from version 3.0.0 published in npm

**Comment by stefanocudini** [comment]
@ppete2 I was busy for work and the new migration of my server, which changed its name to: https://opengeo.tech
