### ISSUE TITLE
In the function _fillRecordsCache, the path of ELSE is unreachable

### ISSUE THREAD

**Issue by XiaoR66** [stefanocudini/leaflet-search#285]
In the function `_fillRecordsCache()`, the `if(this._layer)` judgment branch is error. Because `this._layer` will never be `null` , so the `else`  is unreachable. In early version, is `if(this.options.layer)`.

**Comment by XiaoR66** [comment]
![image](https://user-images.githubusercontent.com/87312030/125285086-da096300-e34c-11eb-9e35-2757934f5b94.png)

![image](https://user-images.githubusercontent.com/87312030/125285183-f907f500-e34c-11eb-97a4-3f23cf216283.png)

**Comment by stefanocudini** [comment]
solver from version 3.0.0 published in npm
