### ISSUE TITLE
Case sensitive with "non-english" character

### ISSUE THREAD

**Issue by soli004** [stefanocudini/leaflet-search#292]
In my url for search there is a mix of all small letters and all with caps.
For example I have: PLACE UPPHÄRAD
When doing a search: 
_place upph_ it shows the correct suggestion but when entering
_place upphä_ it disappear and shows "not found"

If you do a copy and paste from a document it will not work if the text copied is not all caps.
Is there a way to solve this?

**Comment by gg1971** [comment]
https://github.com/stefanocudini/leaflet-search/blob/master/examples/search.php

change
 add u modifier: unicode. Pattern strings are treated as UTF-16. Also causes escape sequences to match unicode characters

function searchInit($text)	//search initial text in titles
{
	$reg = "/^".$_GET['q']."/i**u**";	//initial case insensitive searching  **add u for unicode**
	return (bool)@preg_match($reg, $text['title']);
}

**Comment by soli004** [comment]
Thanks that did solve the problem
