### ISSUE TITLE
How do I use my own local nominatim server?

### ISSUE THREAD

**Issue by martinenkoEduard** [stefanocudini/leaflet-search#302]
How do I use my own local nominatim server?

**Comment by martinenkoEduard** [comment]
Found it -
I need to use something like this - 

map.addControl(new L.Control.Search({
    url: 'http://192.168.56.115:8082/search?format=json&q={s}',
    jsonpParam: 'json_callback',
    propertyName: 'display_name',
    propertyLoc: ['lat','lon'],
    markerLocation: true,
    autoType: false,
    autoCollapse: true,
    minLength: 2,
    zoom:16
}));

**Comment by stefanocudini** [comment]
https://github.com/stefanocudini/leaflet-search/blob/master/examples/geocoding-nominatim.html
