### ISSUE TITLE
Wrong `location` in JS files in Demo page

### ISSUE THREAD

**Issue by sfnprg** [stefanocudini/leaflet-search#320]
Just wanted to report a couple of issues:
JS files linked on [Demo page](https://opengeo.tech/maps/leaflet-search/) under "Download" have:
`if (location.hostname !=='opengeo.tech') {
	location.href = 'https://labs.easyblog.it/';
}`
Which redirect to your website on loading. _leaflet-search.min.js_ is not minified.

I found your package also on a couple of CDNs but they reference to the image (search icon) as `../images/search-icon.png` but that is missing in CDNs.

**Comment by stefanocudini** [comment]
Thanks for reporting this was(now removed) a temporary patch to prevent my server from being used as a CDN by unknown websites.
