### ISSUE TITLE
Geocoding examples broken

### ISSUE THREAD

**Issue by cw-code-1** [stefanocudini/leaflet-search#324]
Hi,
the [google geocoding example](https://opengeo.tech/maps/leaflet-search/examples/geocoding-google.html) and the [nominatim geocoding example](https://opengeo.tech/maps/leaflet-search/examples/geocoding-nominatim.html) are not working for me.

There is an error on loading,  `https://opengeo.tech/labs-common.js ` not found, but I don't think this needed.

Note that this plugin is included in the leaflet-ui plugin and [it works there](https://raruto.github.io/leaflet-ui/examples/leaflet-ui.html), it is using [Leaflet Control Search v3.0.0 - 2021-08-18](https://github.com/Raruto/leaflet-ui/blob/31b300a69f0ae70b1d0c767686ca1c25c541f03a/dist/leaflet-ui-src.js#LL4038C49-L4038C49).

I will try digging into it tomorrow.

**Comment by jt196** [comment]
@cw-code-1 see issue #321 and PR #322. Even with the fix proposed in the latter, I'm still getting an undefined search result. 

Interestingly, the Google example is producing a different error `InvalidValueError: in property address: not a string` to the OSM example: `L.Control.Search.callJsonp is not a function`, though the cause may be related.

**Comment by jt196** [comment]
![image](https://github.com/stefanocudini/leaflet-search/assets/8290163/bbee0628-170f-46bc-a277-10834010cb7e)

I've ended up writing my own...

**Comment by stefanocudini** [comment]
caused by this:
https://github.com/stefanocudini/leaflet-search/pull/322#issuecomment-1669310213

**Comment by stefanocudini** [comment]
solved
