### ISSUE TITLE
Enhancement: search by more than one geojson attribute?

### ISSUE THREAD

**Issue by marks** [stefanocudini/leaflet-search#34]
If possible, could you point me in the right direction for implementing this?

Thanks,

Mark

**Comment by craigmaloney** [comment]
It seems the http://labs.easyblog.it/maps/leaflet-search/examples/multiple-layers.html link is no longer working. Did someone happen to save it? The Wayback machine doesn't seem to have it and I'd like to find a worked example.

**Comment by stefanocudini** [comment]
> It seems the https://opengeo.tech/maps/leaflet-search/examples/multiple-layers.html link is no longer working. Did someone happen to save it? The Wayback machine doesn't seem to have it and I'd like to find a worked example.

now works
