### ISSUE TITLE
Searching a LayerGroup with multiple layers

### ISSUE THREAD

**Issue by phobiac** [stefanocudini/leaflet-search#45]
I have a function that adds markers to different layers based on a certain property. Then I combine them all into one larger LayerGroup. So something like

````javascript
var firstMarkersLayer = L.layerGroup();
var secondMarkersLayer = L.layerGroup();
var thirdMarkersLayer = L.layerGroup();

function that adds markers to the layers //this works fine

var allMarkersLayer = L.layerGroup([firstMarkersLayer, secondMarkersLayer, thirdMarkersLayer]);
````

leaflet-search doesn't appear to be able to search the allMarkersLayer group but will search any of the subgroups fine. Is it possible to have it search the subgroups, or to just define multiple groups for it to search?

**Comment by stefanocudini** [comment]
solved with pull request:
https://github.com/stefanocudini/leaflet-search/pull/79

new demo for this feature:
http://labs.easyblog.it/maps/leaflet-search/examples/multiple-layers.html
