### ISSUE TITLE
Problem with Control Search and Custom Icons.

### ISSUE THREAD

**Issue by Zilant** [stefanocudini/leaflet-search#54]
Hello. I have small problem. I use Leaflet with plugins Control Search and Marker Cluster.

I needed to add a custom icons and I read a tutorial from http://leafletjs.com/examples/custom-icons.html

When I add the code {icon: iconRed} to L.Marker, searching doesnt work anymore.

My code sample:
		
		var markers = L.markerClusterGroup({ disableClusteringAtZoom: 16 });
		
		/////////////

		var controlSearch = new L.Control.Search({layer: markers, initial: false});

		/////////////

		var LeafIcon = L.Icon.extend({
				options: {
					iconSize:     [32, 37],
					iconAnchor:   [16, 37],
					popupAnchor:  [1, -30]
				}
		});
		/////////////
		
		var iconRed = new LeafIcon({iconUrl: './images/marker_icons/red.png'}),
			iconGreen = new LeafIcon({iconUrl: './images/marker_icons/green.png'});
			
		/////////////
		
		var addressPoints = [
			[0,0, "Item 1"],
			[1,1, "Item 2"],
			[2,2, "Item 3"],
			[3,3, "Item 4"]
		];

		/////////////
		
		for (var i = 0; i < addressPoints.length; i++) {
			var a = addressPoints[i];	
			var title = a[2];
			
			marker = new L.Marker(new L.latLng(a[0], a[1]), {icon: iconRed}, {title: title});
			
			marker.bindPopup(title);

			markers.addLayer(marker);
		}
		
		/////////////
		
		map.addLayer(markers);
		
		/////////////
		
		map.addControl(controlSearch);

**Comment by Zilant** [comment]
Promlem solved:
http://stackoverflow.com/questions/28124767/leaflet-control-search-and-custom-icons

**Comment by hmarina** [comment]
I have the same problem but I don know how can I resolve it.
I saw your solution in stackoverflow.

var test = L.icon({
        iconUrl: 'test.png',

        iconSize:     [38, 95], 
        shadowSize:   [50, 64], 
        iconAnchor:   [22, 94],  
        shadowAnchor: [4, 62],  
        popupAnchor:  [-3, -76] 
    });

    var data =var data = [
            {"loc":[41.575330,13.102411], "title":"data1"},
            {"loc":[41.575730,13.002411], "title":"data2"},
            {"loc":[41.807149,13.162994], "title":"data3"},
            {"loc":[41.507149,13.172994], "title":"data4"}];

            var markersLayer = new L.LayerGroup();  //layer contain searched elements
            map.addLayer(markersLayer);

            var controlSearch = new L.Control.Search({layer: markersLayer, initial: false});

            map.addControl( controlSearch );


            for(i in data) {
                    var title = data[i].title,      
                            loc = data[i].loc,        
                            marker = new L.Marker(new L.latLng(loc), {icon: test},{title: title} );
                    marker.bindPopup('title: '+ title );
                    markersLayer.addLayer(marker);
            }
