### ISSUE TITLE
Package still maintained?

### ISSUE THREAD

**Issue by dandv** [stefanocudini/leaflet-search#55]
https://atmospherejs.com/mrt/leaflet-search could use an update for Meteor 0.9+.

To remove `mrt` as a contributor:

```
meteor admin maintainers <your_username>:<your_package> --remove mrt
```

If you were originally the maintainer on the old package system, you can attach your Meteor Developer account at http://atmosphere.meteor.com/accounts, then ping tmeasday to give you ownership of the old package.

**Comment by stefanocudini** [comment]
thank you @dandv!

Please @tmeasday how can I change the owner of my pkg? my  username is stefcud
the command previous comman not work
```
/www/leaflet-search$ meteor admin maintainers stefcud:leaflet-search --remove mrt
Please log in with your Meteor developer account. If you don't have one, you can quickly create one at www.meteor.com.
Username: stefcud
Password:                                     
Removing a maintainer from stefcud:leaflet-search...
Error from package server: Unknown Package [400]
```

**Comment by tmeasday** [comment]
Hi @stefanocudini - have you linked your old atmosphere + MD accounts at atmosphere.meteor.com/account ?

**Comment by stefanocudini** [comment]
@tmeasday I don't know... how can I check this?

**Comment by stefanocudini** [comment]
my account is: https://atmospherejs.com/stefcud

but my pkgs is under mrt prefix... :(

**Comment by tmeasday** [comment]
HI @stefanocudini.

You *are* a maintainer of `mrt:leaflet-search` so I've done all I can unfortunately. Usually what people do from here is:

1. Publish a new version of the package under their own namespace (ie. `stefcud:leaflet-search`).
2. Update the readme of the old package to clearly indicate the new package name.
3. Mark the old package unmigrated (which hides it in the atmosphere UI) `mrt admin set-unmigrated mrt:leaflet-search`.

**Comment by stefanocudini** [comment]
thank you  Tom!
