### ISSUE TITLE
Working With Large DataSets

### ISSUE THREAD

**Issue by bonzysalesman** [stefanocudini/leaflet-search#57]
I am using Leaflet Search with a setup similar to this specific example - http://labs.easyblog.it/maps/leaflet-search/examples/outside.html. I need help with querying a large dataset (55 000 records) without the browser freezing. Is there a way to do ajax server side filtering with ajax?

**Comment by stefanocudini** [comment]
maybe best way is integrate with a browser storage system... like as amplifyjs! ;-)
