### ISSUE TITLE
still can't make the button visible

### ISSUE THREAD

**Issue by xjlin0** [stefanocudini/leaflet-search#59]
Thanks for such a great plug-in. However I still can't make the search box show on my map, where did I go wrong? Thanks again for any comments!

L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
attribution: '© ' + mapLink + ' Contributors',
maxZoom: 18,}).addTo(map);

queryUrl= 'http://localhost:8080/geoserver/jacktest/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=jacktest:jacktest&outputFormat=text/javascript&format_options=callback:callback&featuretype&CQL_FILTER=LAND10='

map.addControl( new L.Control.Search({ url:'queryUrl{s}', jsonpParam:'callback', text:'Color...', markerLocation: true}) );

**Comment by seadour** [comment]
1) You need a semicolon after the queryUrl definition.

2) Try changing `url: 'queryUrl{s}'` to `url: queryUrl + '{s}'`

Let us know if it's still not working after trying those two changes.

**Comment by xjlin0** [comment]
No, the search box still not shown, while the server can respond the json when pasting the url.  Is the '{s}' automatically refer to the user input? Really appreciate your input, do you need me to email you all the codes? Thanks again!

**Comment by seadour** [comment]
> Is the '{s}' automatically refer to the user input?

I'm actually not sure. Hopefully someone else here knows.

> do you need me to email you all the codes?

Normally I would ask you to try it out in a jsfiddle or something, but I see that you're using a locally-hosted geoserver to generate the json. Is there a public geoserver that you can test this with similar query parameters?

Also, can you try changing the queryUrl to specify the actual IP address of localhost? e.g. `http://127.0.0.1:8080`

**Comment by seadour** [comment]
Hey @xjlin0, just checking in. Have you had any luck with this issue?

**Comment by xjlin0** [comment]
Hi seadour, thanks for your help, I still can't make it work.

There are too many properties in each object and there are so many objects in the database, it took 5 sec to get the json back by copy/paste the queryUrl in the browser, and probably that's why the search box never show up.
