### ISSUE TITLE
you code have error in function _recordsFromLayer (leaflet-search.js)

### ISSUE THREAD

**Issue by sashas0928** [stefanocudini/leaflet-search#61]
source code:
     if(layer instanceof L.Marker || L.CircleMarker)

must be:
      if(layer instanceof L.Marker || layer instanceof L.CircleMarker)

**Comment by ghybs** [comment]
Corrected for in commit https://github.com/stefanocudini/leaflet-search/commit/fe72350e9e332d9d8d094dde8a6d162286754698.
