### ISSUE TITLE
bug search Firefox Mobile Android

### ISSUE THREAD

**Issue by SilentT-FR** [stefanocudini/leaflet-search#62]
when i write the term search the plugin do no execute the search.php?....
so when i capture the screen it start the search (lol)

![screenshot_2015-04-28-21-52-50](https://cloud.githubusercontent.com/assets/4253130/7378921/449a2d7e-edf1-11e4-99ec-9f6cb54bd55e.png)
![screenshot_2015-04-28-21-52-54](https://cloud.githubusercontent.com/assets/4253130/7378922/449e68bc-edf1-11e4-936a-c4dca6039662.png)

**Comment by SilentT-FR** [comment]
i precise on chrome mobile android works
Android 4.3

**Comment by stefanocudini** [comment]
@SilentT-FR I'm sorry but I do not have a  Android device having firefox to testing it.
We will wait for resolution by some clever developer

**Comment by SilentT-FR** [comment]
Same problem with my server in front of me(lan)
I use your server for veryfîng is not my serveur the problem 
Sorry for english

**Comment by SilentT-FR** [comment]
ive update to the last release its ok all work fine
