### ISSUE TITLE
Importe geojson file to a leaflet map using Geoserver Url 

### ISSUE THREAD

**Issue by AyadReva** [stefanocudini/leaflet-search#65]
If possible, could you point me in the right direction for implementing this? I really have no idea to do it. i am not so experimented with javascript and php 

Thanks,

Ayad

**Comment by stefanocudini** [comment]
is simple you can use a GeoJSON URL from your geoserver layer... for example using this geoserver demo layer...
```
http://demo.opengeo.org/geoserver/osm/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=osm%3Aadmin_other&maxFeatures=50&outputformat=application%2Fjson
```

**outputformat=application/json**
