### ISSUE TITLE
Leaflet control search click on tooltip marker disappear.

### ISSUE THREAD

**Issue by hemanta25** [stefanocudini/leaflet-search#68]
Am using leaflet control search for searching various markers in our site. When Am clicking on mouse for particular search is working fine. But when Am entering keyboard button all markers are disappear.Please suggest.

**Comment by stefanocudini** [comment]
is incomprehensible

**Comment by hemanta25** [comment]
Am using leaflet control search for searching various markers in our application. When used mouse click for Clipper Tenacious, searching function is working fine find below screen shot -
![mouse_click](https://cloud.githubusercontent.com/assets/5626302/7696613/7a0265c2-fe1c-11e4-8f3b-9f38ee667284.png)
![mouse_click1](https://cloud.githubusercontent.com/assets/5626302/7696614/7a06c004-fe1c-11e4-95d8-e200a73e426d.png).

But when searching Clipper Tenacious and enter keyboard button all markers are disappear.Please suggest how solve these issues.Find screen shot -
![enter_button_key](https://cloud.githubusercontent.com/assets/5626302/7696666/f9c3bbb2-fe1c-11e4-983b-1c636e69d4ec.png)
![Uploading Enter_Button_Key1.png…]()
