### ISSUE TITLE
Possibility to change url search

### ISSUE THREAD

**Issue by SilentT-FR** [stefanocudini/leaflet-search#69]
for my use, when the user select on dropdown value
change the url to execute 
like
VALUE1
q={s}&type=VALUE1
search.seturl('search.php?q={s}&type=' + checked);
ect

var search = map.addControl( new L.Control.Search({
url: 'search.php?q={s}&type=default',
propertyName: 'name',
propertyLoc: ['lat','lng'],
}) );

<select onchange="json()" id="check">
function choice() {
var checked = document.getElementById("check").value;
search.seturl('search.php?q={s}&type=' + checked);
}

**Comment by stefanocudini** [comment]
from version 1.5.7 url option can be an function
https://github.com/stefanocudini/leaflet-search/pull/60

**Comment by SilentT-FR** [comment]
_getUrl return the url actualy used 
but how to change it ?

**Comment by SilentT-FR** [comment]
hmm sorry i understand the var url can be a function and this function return the url in fonction of...

**Comment by SilentT-FR** [comment]
thx sorry for the noise

**Comment by stefanocudini** [comment]
you can set url option like as a function that each time is plugin search execute the same function!

**Comment by stefanocudini** [comment]
read here for an use case, the solution thanks to @realtyjustin:
https://github.com/stefanocudini/leaflet-search/pull/60

**Comment by SilentT-FR** [comment]
hmmm im in wrong way

i have this function
function urlsearch() {
		var checked = document.getElementById("check").value;
		return "search.php?q={s}&type="+ checked;
}
and this

var searchcode = new L.Control.Search({
url: urlsearch(),
});

**Comment by stefanocudini** [comment]
you must pass the function don't the result of the function!!
```
...
var searchcode = new L.Control.Search({
url: urlsearch,
});
```

**Comment by SilentT-FR** [comment]
Oops Great thx
