### ISSUE TITLE
icon on mobile

### ISSUE THREAD

**Issue by SilentT-FR** [stefanocudini/leaflet-search#70]
I use the no mobile css for mobile 
yes is not good but i prefer

you can see the result :

![leaflet search](https://cloud.githubusercontent.com/assets/4253130/8144860/b5471b9a-11f0-11e5-83a2-4d7ec433f9bb.png)

i have see the css and i see that
![sans titre](https://cloud.githubusercontent.com/assets/4253130/8144855/82dcac2e-11f0-11e5-887d-9e8e397d6865.png)

leaflet-bar

and when i add this

![leaflet search with bar](https://cloud.githubusercontent.com/assets/4253130/8144862/c24f885e-11f0-11e5-9947-925bbae35994.png)

it is not perfect but if its closer

**Comment by stefanocudini** [comment]
you must centering the icon usinng css background-position, I think it is simple solution
