### ISSUE TITLE
Update npm and bower repos

### ISSUE THREAD

**Issue by pieterjandesmedt** [stefanocudini/leaflet-search#73]
Hi @stefanocudini , could you please update the npm and bower repos to the latest version (1.5.8)? Requiring the npm module in a project doesn't work and installing via bower gives a warning, I guess because of the version mismatch:
npm:
```sh
Error: Cannot find module 'leaflet-search' from [...]
```
bower:
```sh
bower leaflet-search#*        mismatch Version declared in the json (1.5.7) is different than the resolved one (1.5.8)
```

Thanks!

**Comment by stefanocudini** [comment]
yes sure!  by today I will update it
