### ISSUE TITLE
Does not support duplicate matches

### ISSUE THREAD

**Issue by MuellerMatthew** [stefanocudini/leaflet-search#74]
Currently when searching for a record match from a map layer, this plugin will not return multiple identical matching fields.  For example:  http://labs.easyblog.it/maps/leaflet-search/examples/simple.html in this example, if there were 2 or more markers which had a title of "green" the search field would only return a single "green" value.

**Comment by stefanocudini** [comment]
the key of searching is the title.. then the titles is uniques

**Comment by stefanocudini** [comment]
you can use additional identifier for titles for "green 1" "green 2" "green 3"
