### ISSUE TITLE
use the marker search from the code (dynamically) 

### ISSUE THREAD

**Issue by younesszah** [stefanocudini/leaflet-search#76]
how can I use the search functionality in the background (from my javascript code) to display the same search result (find the marker+pan+zoom). 
Thank you a lot !

**Comment by stefanocudini** [comment]
what?

**Comment by younesszah** [comment]
Hi Dear Stefano, 
I am implementing a voice command to search the markers. til now I can get the name spoken by the user but I dont know how to combine this with your search control to zoom to the marker.. can i give the marker name to search in the code and get the same classic result : zooming to the marker

**Comment by stefanocudini** [comment]
this plugin is a interface to an webservice that search real data inside a geographic database.. for others behaviours you cloud be try other library

**Comment by stefanocudini** [comment]
It's just added new method that allow this!  From version 1.6.1
https://github.com/stefanocudini/leaflet-search/commit/f2d8ff44a835132b111f2e1517306998c00b9b5e

example of use:
http://labs.easyblog.it/maps/leaflet-search/examples/methods.html

**Comment by younesszah** [comment]
Thanks Habibi! That would be of a great help !

**Comment by stefanocudini** [comment]
who is Habibi?
