### ISSUE TITLE
Get marker of markerLocation

### ISSUE THREAD

**Issue by neversun** [stefanocudini/leaflet-search#86]
Hey out there,

I'm using the following code to add a search control to my leaflet map:

    map.addControl(new L.Control.Search({
      url: 'http://nominatim.openstreetmap.org/search?format=json&q={s}',
      jsonpParam: 'json_callback',
      propertyName: 'display_name',
      propertyLoc: ['lat', 'lon'],
      circleLocation: false,
      markerLocation: true,
      autoType: false,
      autoCollapse: true,
      minLength: 2,
      zoom: 16
    }));

How do I get the marker object of the `markerLocation: true` marker, which is set as I click on a search result? I need both lat and lon coordinates of the marker set.

**Comment by stefanocudini** [comment]
you cann use a event *search_locationfound*
https://github.com/stefanocudini/leaflet-search/blob/master/dist/leaflet-search.src.js#L25
