### ISSUE TITLE
Getting data from Geoserver jsonp request

### ISSUE THREAD

**Issue by mtravis** [stefanocudini/leaflet-search#87]
Hi 

I'm trying to use your fantastic plugin to return data from a geoserver request but I have to use jsonp.The request gets the data but doesn't search for it. 

What am I doing wrong?

Here's my code:

	function searchByAjax(text, callResponse)
	{
	
		$.ajax({
			url: 'http://maps.nationalparks.gov.uk/geoserver/dartmoor/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=dartmoor:dnpa_guidedwalks&outputFormat=application/json',
			type: 'GET',
			data: {CQL_FILTER:"walkname="+"'"+text+"'"},
			dataType: 'jsonp',
			success: function(json) {
				callResponse(json);
			}
		});
	}

	map.addControl( new L.Control.Search(
	{	
	propertyName: 'walkname', 
	propertyLoc: ['lat','long'],
	callData: searchByAjax,
	minLength: 3,	
	tooltipLimit:10,
	text:'Search for a Walk...', 
	textErr: 'Application not found',
	markerLocation: true, 
	position: 'topleft' ,
	circleLocation: false,
	animateLocation: false,
	autoCollapse: true,
	collapsed: false,
	zoom: 13}
	) 
	);

**Comment by stefanocudini** [comment]
hi @mtravis now the last version have few options renamed, for example: callData to sourceData
try it

**Comment by mtravis** [comment]
Have you got an working example?

**Comment by stefanocudini** [comment]
sure!
here:
https://github.com/stefanocudini/leaflet-search/blob/master/examples/jsonp-filtered.html#L46

**Comment by mtravis** [comment]
Thank you.

**Comment by stefanocudini** [comment]
for JSONP and simple GET request **leaflet-search** don't need jQuery

**Comment by marfeca94** [comment]
Stefano, si può vedere un esempio della ricerca di un dato da un wfs?

Esempio:


function formatJSON(rawjson) {	//callback that remap fields name
		var json = {},
			key, loc, disp = [];
		for(var i in rawjson)
		{
			disp = rawjson[i].?????????.split(',');	
			key = disp[0] +', '+ disp[1];
			
			loc = L.latLng( rawjson[i].lat, rawjson[i].lon );
			
			json[ key ]= loc;	//key,value format
		}
		
		return json;
	}
	
	var searchOpts = {
			url: '?????',
			jsonpParam: 'json_callback',
			formatData: formatJSON,
			zoom: 10,
			minLength: 2,
			autoType: false,
			marker: {
				icon: false,
				animate: false
			}
		};
		
	map.addControl( new L.Control.Search(searchOpts) );
