### ISSUE TITLE
Add bower dependencies

### ISSUE THREAD

**Issue by gavioto** [stefanocudini/leaflet-search#91]
It could be very useful adding bower dependencies to the plugin

  "dependencies": {
      "leaflet": ">=0.7"
  }

When using this module from webjars, for example, dependencies are also read from bower

I know the plugin depends on 'leaflet'. Any other dependency? It could be also added.

Edit:
I found package.json contains dependencies, but now bower.json. It is an active discussion here https://github.com/bower/bower/issues/1626 https://github.com/bower/bower/issues/1957 
it seems it could be automated..

**Comment by stefanocudini** [comment]
can you create a pull request for this?
tnk

**Comment by gavioto** [comment]
done
