### ISSUE TITLE
ssl support

### ISSUE THREAD

**Issue by miton18** [stefanocudini/leaflet-search#92]
there are any way to enable https on requests, my website use ssl, and browsers doesn't like to call a non ssl ressource

**Comment by stefanocudini** [comment]
mmmh are you just specifed *https://* in leaflet-search option url?

**Comment by miton18** [comment]
this will overide the default http:// ?

**Comment by stefanocudini** [comment]
where is the "default" http://??  leaflet-search don't contain default urls
