### ISSUE TITLE
Search CSV atributes

### ISSUE THREAD

**Issue by joshdickerson92** [stefanocudini/leaflet-search#97]
I am using [Leaflet GeoCSV](https://github.com/joker-x/Leaflet.geoCSV) to bring through a series of points. Would it be possible to use Leaflet Search to query attributes from multiple columns of this CSV? e.g. Search from a column with a Project Number and a column with a Project Name from the same search bar?

**Comment by p4535992** [comment]
This question can be related to a my old issue #89 , i can't figured out a solution for solve that by myself (i don't try very hard to solve that  XD).
Anyway i solved (at least for me) with a brute force solution, building a function for convert the csv content to a geojson/json data content, (your csv file must have at least  two columns for latitude and longitude for doing that), and create a search button with this other leaflet plugin [leaflet-fusesearch](https://github.com/naomap/leaflet-fusesearch) for make a research, a little more hard to implement maybe , but you can do your research on multiple field of the json data (which is equivalent to make a research to multiple field of the csv file you have converted to json attributes).

**Comment by reyemtm** [comment]
I am searching just fine with passing an omnivore.csv to L.geoJson. As far as multiple fields, one idea would be to create another field in the csv with all the search terms added to that field.

**Comment by p4535992** [comment]
yes, it's a good alternative solution use omnivore. Here a example of what you want: [link to example] (https://www.mapbox.com/mapbox.js/example/v1.0.0/filtering/), in my case I did not use omnivore for two reasons:

- My  project does'nt use Node.js. (although now I was allowed to use [jspm](http://jspm.io/) that solves all problems related to the use of npm,amd,nodes packages).
- I need to load the markers in different layers depending on the value of a particular field csv, this omnivore does not allow you to do it (I think).
