### ISSUE TITLE
select first tooltip-target on return

### ISSUE THREAD

**Issue by Sekulidan** [stefanocudini/leaflet-search#99]
Hi,

if the search has only one target, it gets selected by hitting return.

Feature-request: add an option to select the first element of the result list if there are many. 
Like the google-button "I'm Feeling Lucky".

**Comment by stefanocudini** [comment]
good idea!

try to fork and implement it please!
I think this may be a good new feature jointly the history search

**Comment by Sekulidan** [comment]
I've implemented this because my boss wanted to use the 'return' key after typing the search-string.

I've a local fork of this (not versioned) containing [#95 recursive search](https://github.com/stefanocudini/leaflet-search/issues/95),  [#96](https://github.com/stefanocudini/leaflet-search/issues/96) and a minor adaption because leaflet in 1.0.0-beta.2 has a bug that it creates a click-event at the key-press in search addon.

I'm trying a fork with only this change

**Comment by Sekulidan** [comment]
Hi, I've [branched there](https://github.com/Sekulidan/leaflet-search). It's very simple - feel free to rename/move the option.

Greeting: Sekulidan

**Comment by stefanocudini** [comment]
@Sekulidan  implemented new option: firstTipSubmit from version 2.0.0
